SELECT
	AFFILIATOR.NAME
   ,CPF_CNPJ
   ,SERVICE_AMOUNT
FROM AFFILIATOR
JOIN SERVICES_AVAILABLE
	ON SERVICES_AVAILABLE.COD_AFFILIATOR = AFFILIATOR.COD_AFFILIATOR
JOIN ITEMS_SERVICES_AVAILABLE
	ON ITEMS_SERVICES_AVAILABLE.COD_ITEM_SERVICE = SERVICES_AVAILABLE.COD_ITEM_SERVICE
WHERE ITEMS_SERVICES_AVAILABLE.COD_ITEM_SERVICE = 11
AND SERVICES_AVAILABLE.ACTIVE = 1
AND COD_EC IS NULL