INSERT INTO SITUATION (NAME, VIEWER, TRANSACTION_VIEWER, PAYMENT_VIEW) VALUES ('PRE-APPROVED', 1, 1, NULL)
INSERT INTO TRADUCTION_SITUATION (COD_SITUATION, LANGUAGE, SITUATION_TR) VALUES ((SELECT COD_SITUATION FROM SITUATION WHERE NAME = 'PRE-APPROVED'), 'PORTUGUES', 'PRÉ-APROVADA')
GO
IF NOT EXISTS (SELECT
		1
	FROM sys.columns
	WHERE NAME = N'PRE_APPROVED'
	AND object_id = OBJECT_ID(N'TRANSACTION'))
BEGIN
ALTER TABLE [TRANSACTION]
ADD [PRE_APPROVED] INT DEFAULT 0
END

GO



IF OBJECT_ID('SP_FD_TRANSACTION_TO_APPROVE') IS NOT NULL DROP PROCEDURE SP_FD_TRANSACTION_TO_APPROVE;
GO
CREATE PROCEDURE SP_FD_TRANSACTION_TO_APPROVE
(
	@CODE_TRAN VARCHAR(255)
)
AS
BEGIN
SELECT
	ACQUIRER_KEYS_CREDENTIALS.[NAME]
   ,ACQUIRER_KEYS_CREDENTIALS.[VALUE]
FROM [TRANSACTION] WITH (NOLOCK)
INNER JOIN PRODUCTS_ACQUIRER
	ON PRODUCTS_ACQUIRER.COD_PR_ACQ = [TRANSACTION].COD_PR_ACQ
INNER JOIN ACQUIRER
	ON ACQUIRER.COD_AC = PRODUCTS_ACQUIRER.COD_AC
INNER JOIN ACQUIRER_KEYS_CREDENTIALS
	ON ACQUIRER.COD_AC = ACQUIRER_KEYS_CREDENTIALS.COD_AC
INNER JOIN SITUATION
	ON SITUATION.COD_SITUATION = [TRANSACTION].COD_SITUATION
WHERE [TRANSACTION].CODE = @CODE_TRAN
AND SITUATION.NAME = 'PRE-APPROVED'

IF @@rowcount < 1 
	THROW 60002, '010', 1;
END;

GO
IF OBJECT_ID('SP_UP_TRANSACTION_ON') IS NOT NULL DROP PROCEDURE SP_UP_TRANSACTION_ON;
GO
CREATE PROCEDURE [dbo].[SP_UP_TRANSACTION_ON]              
/*----------------------------------------------------------------------------------------              
Procedure Name: [SP_UP_TRANSACTION]              
Project.......: TKPP              
------------------------------------------------------------------------------------------              
Author VERSION Date Description              
------------------------------------------------------------------------------------------              
Kennedy Alef V1 27/07/2018 Creation              
Rodrigo Carvalho V2 12/12/2018 Creation              
Lucas Aguiar v3 2019-04-17 Add parâmetro e rotina de aw. titles              
------------------------------------------------------------------------------------------*/              
(              
@CODE_TRAN VARCHAR(200),              
@SITUATION VARCHAR(100),              
@DESCRIPTION VARCHAR(200),              
@CURRENCY VARCHAR(100),          
@COD_PROD_ACQ INT = NULL,        
@COD_AC INT = NULL      
)              
AS              
DECLARE @CONT INT;
    
        
          
              
DECLARE @SIT VARCHAR(100);
    
        
          
              
DECLARE @BRANCH INT
    
        
          
DECLARE @COD_ASS_TR_COMP INT;
    
        
BEGIN

SELECT
	@COD_ASS_TR_COMP = ASS_TR_TYPE_COMP.COD_ASS_TR_COMP
FROM ASS_TR_TYPE_COMP
INNER JOIN [TRANSACTION] WITH (NOLOCK)
	ON [TRANSACTION].CODE = @CODE_TRAN
		AND [TRANSACTION].PLOTS BETWEEN PLOT_INI AND PLOT_END
INNER JOIN BRAND
	ON BRAND.NAME = [TRANSACTION].BRAND
		AND BRAND.COD_TTYPE = [TRANSACTION].COD_TTYPE
		AND ASS_TR_TYPE_COMP.COD_BRAND = BRAND.COD_BRAND
WHERE ASS_TR_TYPE_COMP.COD_SOURCE_TRAN = 1
AND ACTIVE = 1
AND ASS_TR_TYPE_COMP.COD_AC = @COD_AC

SET @CONT = 1;
SELECT
	@CONT = COD_TRAN
   ,@SIT = SITUATION.NAME
FROM [TRANSACTION]
INNER JOIN SITUATION
	ON SITUATION.COD_SITUATION = [TRANSACTION].COD_SITUATION
WHERE CODE = @CODE_TRAN
IF @CONT < 1
	OR @CONT IS NULL
THROW 60002, '601', 1;
UPDATE PROCESS_BG_STATUS
SET STATUS_PROCESSED = 0
   ,MODIFY_DATE = GETDATE()
WHERE CODE = @CONT
AND COD_TYPE_PROCESS_BG = 1
IF @SITUATION = 'APPROVED'
BEGIN
EXEC SP_REG_HIST_TRANSACTION @CODE_TR = @CODE_TRAN;
UPDATE [TRANSACTION]
SET COD_SITUATION = 1
   ,MODIFY_DATE = GETDATE()
   ,COMMENT = @DESCRIPTION
   ,COD_CURRRENCY = (SELECT
			COD_CURRRENCY
		FROM CURRENCY
		WHERE NUM = @CURRENCY)
   ,[TRANSACTION].COD_PR_ACQ = ISNULL(@COD_PROD_ACQ, [TRANSACTION].COD_PR_ACQ)
   ,[TRANSACTION].COD_ASS_TR_COMP = ISNULL(@COD_ASS_TR_COMP, [TRANSACTION].COD_ASS_TR_COMP)
WHERE [TRANSACTION].CODE = @CODE_TRAN;
IF @@rowcount < 1
THROW 60002, '002', 1
END
ELSE
IF @SITUATION = 'PENDENT'
BEGIN
EXEC SP_REG_HIST_TRANSACTION @CODE_TR = @CODE_TRAN;
UPDATE [TRANSACTION]
SET COD_SITUATION = 19
   ,MODIFY_DATE = GETDATE()
   ,COMMENT = @DESCRIPTION
   ,[TRANSACTION].COD_PR_ACQ = ISNULL(@COD_PROD_ACQ, [TRANSACTION].COD_PR_ACQ)
   ,[TRANSACTION].COD_ASS_TR_COMP = ISNULL(@COD_ASS_TR_COMP, [TRANSACTION].COD_ASS_TR_COMP)
WHERE [TRANSACTION].CODE = @CODE_TRAN;
IF @@rowcount < 1
THROW 60002, '002', 1
END
ELSE
IF @SITUATION = 'CONFIRMED'
BEGIN
IF @SIT = @SITUATION
THROW 60002, '603', 1
EXEC SP_REG_HIST_TRANSACTION @CODE_TR = @CODE_TRAN;
UPDATE [TRANSACTION]
SET COD_SITUATION = 3
   ,MODIFY_DATE = GETDATE()
   ,COMMENT = @DESCRIPTION
   ,[TRANSACTION].COD_PR_ACQ = ISNULL(@COD_PROD_ACQ, [TRANSACTION].COD_PR_ACQ)
   ,[TRANSACTION].COD_ASS_TR_COMP = ISNULL(@COD_ASS_TR_COMP, [TRANSACTION].COD_ASS_TR_COMP)
WHERE [TRANSACTION].CODE = @CODE_TRAN;
IF @@rowcount < 1
THROW 60002, '002', 1
DELETE FROM TRANSACTION_PENDENT_TREATMENT
WHERE TID = @CODE_TRAN
EXECUTE [SP_GEN_TITLES_TRANS] @COD_TRAN = @CODE_TRAN
END
ELSE
IF @SITUATION = 'AWAITING TITLES'
BEGIN
IF @SIT = @SITUATION
THROW 60002, '603', 1
EXEC SP_REG_HIST_TRANSACTION @CODE_TR = @CODE_TRAN;
UPDATE [TRANSACTION]
SET COD_SITUATION = 22
   ,MODIFY_DATE = GETDATE()
   ,COMMENT = '206 - AGUARDANDO TITULOS'
   ,[TRANSACTION].COD_PR_ACQ = ISNULL(@COD_PROD_ACQ, [TRANSACTION].COD_PR_ACQ)
   ,[TRANSACTION].COD_ASS_TR_COMP = ISNULL(@COD_ASS_TR_COMP, [TRANSACTION].COD_ASS_TR_COMP)
WHERE [TRANSACTION].CODE = @CODE_TRAN;
IF @@rowcount < 1
THROW 60002, '002', 1
DELETE FROM TRANSACTION_PENDENT_TREATMENT
WHERE TID = @CODE_TRAN;
END
ELSE
IF @SITUATION = 'DENIED ACQUIRER'
BEGIN
EXEC SP_REG_HIST_TRANSACTION @CODE_TR = @CODE_TRAN;
UPDATE [TRANSACTION]
SET COD_SITUATION = 2
   ,MODIFY_DATE = GETDATE()
   ,COD_CURRRENCY = (SELECT
			COD_CURRRENCY
		FROM CURRENCY
		WHERE NUM = @CURRENCY)
   ,COMMENT = @DESCRIPTION
   ,[TRANSACTION].COD_PR_ACQ = ISNULL(@COD_PROD_ACQ, [TRANSACTION].COD_PR_ACQ)
   ,[TRANSACTION].COD_ASS_TR_COMP = ISNULL(@COD_ASS_TR_COMP, [TRANSACTION].COD_ASS_TR_COMP)
WHERE [TRANSACTION].CODE = @CODE_TRAN;
IF @@rowcount < 1
THROW 60002, '002', 1
END;
IF @SITUATION = 'UNDONE'
BEGIN
EXEC SP_REG_HIST_TRANSACTION @CODE_TR = @CODE_TRAN;
UPDATE [TRANSACTION]
SET COD_SITUATION = 10
   ,MODIFY_DATE = GETDATE()
   ,COMMENT = @DESCRIPTION
   ,[TRANSACTION].COD_PR_ACQ = ISNULL(@COD_PROD_ACQ, [TRANSACTION].COD_PR_ACQ)
   ,[TRANSACTION].COD_ASS_TR_COMP = ISNULL(@COD_ASS_TR_COMP, [TRANSACTION].COD_ASS_TR_COMP)
WHERE [TRANSACTION].CODE = @CODE_TRAN;
IF @@rowcount < 1
THROW 60002, '002', 1
END;
--OR @SITUATION = ''              
ELSE
IF @SITUATION = 'PRE-APPROVED'
BEGIN
EXEC SP_REG_HIST_TRANSACTION @CODE_TR = @CODE_TRAN;
UPDATE [TRANSACTION]
SET COD_SITUATION = 32
   ,MODIFY_DATE = GETDATE()
   ,COMMENT = @DESCRIPTION
   ,COD_CURRRENCY = (SELECT
			COD_CURRRENCY
		FROM CURRENCY
		WHERE NUM = @CURRENCY)
   ,[TRANSACTION].COD_PR_ACQ = ISNULL(@COD_PROD_ACQ, [TRANSACTION].COD_PR_ACQ)
   ,[TRANSACTION].COD_ASS_TR_COMP = ISNULL(@COD_ASS_TR_COMP, [TRANSACTION].COD_ASS_TR_COMP)
   ,[TRANSACTION].PRE_APPROVED = 1
WHERE [TRANSACTION].CODE = @CODE_TRAN;
IF @@rowcount < 1
THROW 60002, '002', 1
END
IF @SITUATION = 'FAILED'
BEGIN
EXEC SP_REG_HIST_TRANSACTION @CODE_TR = @CODE_TRAN;
UPDATE [TRANSACTION]
SET COD_SITUATION = 7
   ,MODIFY_DATE = GETDATE()
   ,COMMENT = @DESCRIPTION
   ,[TRANSACTION].COD_PR_ACQ = ISNULL(@COD_PROD_ACQ, [TRANSACTION].COD_PR_ACQ)
   ,[TRANSACTION].COD_ASS_TR_COMP = ISNULL(@COD_ASS_TR_COMP, [TRANSACTION].COD_ASS_TR_COMP)
WHERE [TRANSACTION].CODE = @CODE_TRAN;
IF @@rowcount < 1
THROW 60002, '002', 1
END;
ELSE
IF @SITUATION = 'CANCELED'
BEGIN
IF (@SIT = 'AWAITING TITLES')
BEGIN
IF @SIT = @SITUATION
THROW 60002, '703', 1
EXEC SP_REG_HIST_TRANSACTION @CODE_TR = @CODE_TRAN;
UPDATE [TRANSACTION]
SET COD_SITUATION = 6
   ,MODIFY_DATE = GETDATE()
   ,COMMENT = @DESCRIPTION
   ,[TRANSACTION].COD_PR_ACQ = ISNULL(@COD_PROD_ACQ, [TRANSACTION].COD_PR_ACQ)
   ,[TRANSACTION].COD_ASS_TR_COMP = ISNULL(@COD_ASS_TR_COMP, [TRANSACTION].COD_ASS_TR_COMP)
WHERE [TRANSACTION].CODE = @CODE_TRAN;
IF @@rowcount < 1
THROW 60002, '002', 1
UPDATE TRANSACTION_TITLES
SET TRANSACTION_TITLES.COD_SITUATION = 6
   ,MODIFY_DATE = GETDATE()
   ,COMMENT = @DESCRIPTION
FROM TRANSACTION_TITLES
INNER JOIN [TRANSACTION]
	ON [TRANSACTION].COD_TRAN = TRANSACTION_TITLES.COD_TRAN
WHERE [TRANSACTION].CODE = @CODE_TRAN
UPDATE RELEASE_ADJUSTMENTS
SET RELEASE_ADJUSTMENTS.COD_SITUATION = 6
FROM RELEASE_ADJUSTMENTS
INNER JOIN POSWEB_DATA_TRANSACTION
	ON RELEASE_ADJUSTMENTS.COD_POS_DATA = POSWEB_DATA_TRANSACTION.COD_POS_DATA
INNER JOIN [TRANSACTION]
	ON [TRANSACTION].COD_TRAN = POSWEB_DATA_TRANSACTION.COD_TRAN
WHERE [TRANSACTION].CODE = @CODE_TRAN
END;
ELSE
BEGIN
IF @SIT = @SITUATION
THROW 60002, '703', 1
SELECT
	@CONT = COUNT(*)
FROM TRANSACTION_TITLES
INNER JOIN [TRANSACTION]
	ON [TRANSACTION].COD_TRAN = TRANSACTION_TITLES.COD_TRAN
WHERE [TRANSACTION].CODE = @CODE_TRAN
AND TRANSACTION_TITLES.COD_SITUATION != 4
IF @CONT > 0
THROW 60002, '704', 1
EXEC SP_REG_HIST_TRANSACTION @CODE_TR = @CODE_TRAN;
UPDATE [TRANSACTION]
SET COD_SITUATION = 6
   ,MODIFY_DATE = GETDATE()
   ,COMMENT = @DESCRIPTION
   ,[TRANSACTION].COD_PR_ACQ = ISNULL(@COD_PROD_ACQ, [TRANSACTION].COD_PR_ACQ)
   ,[TRANSACTION].COD_ASS_TR_COMP = ISNULL(@COD_ASS_TR_COMP, [TRANSACTION].COD_ASS_TR_COMP)
WHERE [TRANSACTION].CODE = @CODE_TRAN;
IF @@rowcount < 1
THROW 60002, '002', 1
UPDATE TRANSACTION_TITLES
SET TRANSACTION_TITLES.COD_SITUATION = 6
   ,MODIFY_DATE = GETDATE()
   ,COMMENT = @DESCRIPTION
FROM TRANSACTION_TITLES
INNER JOIN [TRANSACTION]
	ON [TRANSACTION].COD_TRAN = TRANSACTION_TITLES.COD_TRAN
WHERE [TRANSACTION].CODE = @CODE_TRAN
UPDATE RELEASE_ADJUSTMENTS
SET RELEASE_ADJUSTMENTS.COD_SITUATION = 6
FROM RELEASE_ADJUSTMENTS
INNER JOIN POSWEB_DATA_TRANSACTION
	ON RELEASE_ADJUSTMENTS.COD_POS_DATA = POSWEB_DATA_TRANSACTION.COD_POS_DATA
INNER JOIN [TRANSACTION]
	ON [TRANSACTION].COD_TRAN = POSWEB_DATA_TRANSACTION.COD_TRAN
WHERE [TRANSACTION].CODE = @CODE_TRAN
END;
END
END