IF NOT EXISTS (SELECT
		1
	FROM sys.columns
	WHERE NAME = N'SENT'
	AND object_id = OBJECT_ID(N'USERS'))
BEGIN
ALTER TABLE USERS
ADD SENT INT
END
GO

UPDATE USERS
SET SENT = 1

GO
IF OBJECT_ID('SP_LS_USERS_TO_SEND') IS NOT NULL DROP PROCEDURE SP_LS_USERS_TO_SEND
GO
CREATE PROCEDURE SP_LS_USERS_TO_SEND
AS
BEGIN

SELECT
	USERS.COD_USER
   ,IDENTIFICATION
   ,EMAIL
   ,COD_ACCESS
   ,AFFILIATOR.SUBDOMAIN
FROM USERS
INNER JOIN PROVISORY_PASS_USER
	ON PROVISORY_PASS_USER.COD_USER = USERS.COD_USER
		AND PROVISORY_PASS_USER.ACTIVE = 1
LEFT JOIN AFFILIATOR
	ON AFFILIATOR.COD_AFFILIATOR = USERS.COD_AFFILIATOR
WHERE ISNULL(SENT, 0) = 0

END

GO
IF OBJECT_ID('SP_UP_SENT_USER') IS NOT NULL DROP PROCEDURE SP_UP_SENT_USER
GO

CREATE PROCEDURE SP_UP_SENT_USER
(
	@COD_USER INT
)
AS
BEGIN

UPDATE USERS
SET SENT = 1
WHERE COD_USER = @COD_USER

END