UPDATE CITY SET
CITY_CODE = '5212501'
WHERE NAME = 'LUIZIANIA'
GO
UPDATE CITY SET
CITY_CODE = '2303709'
WHERE NAME = 'CAUCAIA'
GO
UPDATE CITY SET
CITY_CODE = '3532801'
WHERE NAME = 'NOVA ITAPIREMA (NOVA ALIANÇA)'
GO
UPDATE CITY SET
CITY_CODE = '4204194'
WHERE NAME = 'CHAPADA DO LAGEADO'
GO
UPDATE CITY SET
CITY_CODE = '3541109'
WHERE NAME = 'SÃO LUIZ DO GUARICANGA (PRESIDENTE ALVES)'
GO
UPDATE CITY SET
CITY_CODE = '2925303'
WHERE COD_CITY = 11216
GO
UPDATE CITY SET
CITY_CODE = '2933307'
WHERE NAME = 'CABECEIRA DO JIBOIA (VITORIA DA CONQUISTA)'
GO
UPDATE CITY SET
CITY_CODE = '5219753'
WHERE NAME = 'SANTO ANTÔNIO DO DESCOBERTO'
GO
UPDATE CITY SET
CITY_CODE = '4204194'
WHERE NAME = 'SCHAPADA DO LAGEADO'
GO
UPDATE CITY SET
CITY_CODE = '4204194'
WHERE NAME = 'SCHAPADA DO LAGEADO'
GO
UPDATE CITY SET
CITY_CODE = '4125209'
WHERE NAME = 'SÃO JORGE DO OESTE'
GO
UPDATE CITY SET
CITY_CODE = '4125209'
WHERE NAME = 'SÃO JORGE DO OESTE'
GO
UPDATE CITY SET
CITY_CODE = '3148400'
WHERE NAME = 'PAULISTA'
GO
UPDATE CITY SET
CITY_CODE = '4111209'
WHERE NAME = 'ITAPEJARA DO OESTE'
GO
UPDATE CITY SET
CITY_CODE = '4202859'
WHERE NAME = 'BRAÇO DO TROM'
GO
UPDATE CITY SET
CITY_CODE = '4106605'
WHERE NAME = 'CAFEEIROS (CRUZEIRO DO OESTE)'
GO
UPDATE CITY SET
CITY_CODE = '4128104'
WHERE NAME = 'SERRA DOS DOURADOS (UMUARAMA)'
GO
UPDATE CITY SET
CITY_CODE = '3162302'
WHERE NAME = 'SÃO JOSÉ DA MATA (CAMPINA GRANDE)'
GO
UPDATE CITY SET
CITY_CODE = '3162302'
WHERE NAME = 'SÃO JOSÉ DA MATA (CAMPINA GRANDE)'
GO
UPDATE CITY SET
CITY_CODE = '4317103'
WHERE NAME = 'SANTANA DO LIVRAMENTO'
GO
UPDATE CITY SET
CITY_CODE = '5200258'
WHERE NAME = 'ÁGUAS LINDAS DE GOIÁS'
GO
UPDATE CITY SET
CITY_CODE = '1301852'
WHERE NAME = 'CACAU PIRÊRA (IRANDUBA)'
GO
UPDATE CITY SET
CITY_CODE = '1301852'
WHERE NAME = 'CACAU PIRÊRA (IRANDUBA)'
GO
UPDATE CITY SET
CITY_CODE = '1718204'
WHERE NAME = 'LUZIMANGUES (PORTO NACIONAL)'
GO
UPDATE CITY SET
CITY_CODE = '2602902'
WHERE NAME = 'SANTO AGOSTINHO (CABO DE SANTO AGOSTINHO)'
GO
UPDATE CITY SET
CITY_CODE = '2918407'
WHERE NAME = 'PINHÕES (JUAZEIRO)'
GO
UPDATE CITY SET
CITY_CODE = '3534302'  
WHERE NAME = 'ORLÂNDIA'
GO
UPDATE CITY SET
CITY_CODE = '2408102'  
WHERE NAME = 'NATAL'
GO
UPDATE CITY SET
CITY_CODE = '4107207'  
WHERE NAME = 'DOIZ VIZINHOS'
GO
UPDATE CITY SET
CITY_CODE = '4123006'  
WHERE NAME = 'SALTO DO LONTRAA'
GO
UPDATE CITY SET
CITY_CODE = '5001102'  
WHERE NAME = 'PIRAPUTANGA (AQUIDAUANA)'
GO
UPDATE CITY SET
CITY_CODE = '4125209'  
WHERE NAME = 'SAO JORGE DOESTE'
GO
UPDATE CITY SET
CITY_CODE = '4107207'  
WHERE NAME = 'DOIS DIZINHOS'
GO
UPDATE CITY SET
CITY_CODE = '4107207'  
WHERE NAME = 'SOBRAL'
GO
UPDATE CITY SET
CITY_CODE = '4103222'  
WHERE NAME = 'CENTRO'
GO
