CREATE PROCEDURE SP_GET_CREDENTIALS_ONLINE      
(      
 @COD_AC INT,    
 @CODE_EC INT = NULL    
)      
AS      
BEGIN
SELECT
	ACQUIRER_KEYS_CREDENTIALS.NAME
   ,ACQUIRER_KEYS_CREDENTIALS.[VALUE]
FROM ACQUIRER_KEYS_CREDENTIALS
INNER JOIN ACQUIRER
	ON ACQUIRER.COD_AC = ACQUIRER_KEYS_CREDENTIALS.COD_AC
WHERE ACQUIRER_KEYS_CREDENTIALS.COD_AC = @COD_AC
AND (ACQUIRER_KEYS_CREDENTIALS.CODE_EC = @CODE_EC
OR ACQUIRER_KEYS_CREDENTIALS.CODE_EC IS NULL)
END;

INSERT INTO ACQUIRER_KEYS_CREDENTIALS (NAME, VALUE, COD_AC, CODE_EC)
	VALUES ('GW_ID', 1, 25, 680547)
INSERT INTO ACQUIRER_KEYS_CREDENTIALS (NAME, VALUE, COD_AC, CODE_EC)
	VALUES ('ACQ_GROUP', 'PagSeguro', 25, 680547)
INSERT INTO ACQUIRER_KEYS_CREDENTIALS (NAME, VALUE, COD_AC, CODE_EC)
	VALUES ('ACQ_NAME', (SELECT NAME FROM ACQUIRER WHERE COD_AC = 25), 25, 680547)
INSERT INTO ACQUIRER_KEYS_CREDENTIALS (NAME, VALUE, COD_AC, CODE_EC)
	VALUES ('EC', 'CELER', 25, 680547)
INSERT INTO ACQUIRER_KEYS_CREDENTIALS (NAME, VALUE, COD_AC, CODE_EC)
	VALUES ('PRIORITY', 1, 25, 680547)
INSERT INTO ACQUIRER_KEYS_CREDENTIALS (NAME, VALUE, COD_AC, CODE_EC)
	VALUES ('EMAIL', 'brunokazuo1@gmail.com', 25, 680547)
INSERT INTO ACQUIRER_KEYS_CREDENTIALS (NAME, VALUE, COD_AC, CODE_EC)
	VALUES ('TOKEN', '478B606F6A674A0793178E7864E85524', 25, 680547)