IF OBJECT_ID('ITEMS_LOT_CNAB_PAYMENT') IS NOT NULL DROP TABLE ITEMS_LOT_CNAB_PAYMENT;
GO
IF OBJECT_ID('CNAB_OCCURRENCES') IS NOT NULL DROP TABLE CNAB_OCCURRENCES;
GO
IF OBJECT_ID('LOT_CNAB_PAYMENT') IS NOT NULL DROP TABLE LOT_CNAB_PAYMENT;
GO
IF OBJECT_ID('CNAB_FILE_LOT') IS NOT NULL DROP TABLE CNAB_FILE_LOT;
GO
IF OBJECT_ID('SP_REG_LOT_CNAB_PAYMENT') IS NOT NULL DROP PROCEDURE SP_REG_LOT_CNAB_PAYMENT
GO
IF OBJECT_ID('SP_REG_ITEMS_LOT_CNAB_PAYMENT') IS NOT NULL DROP PROCEDURE SP_REG_ITEMS_LOT_CNAB_PAYMENT
GO
IF OBJECT_ID('SP_FD_SCHEDULE_FILE') IS NOT NULL DROP PROCEDURE SP_FD_SCHEDULE_FILE
GO
IF TYPE_ID('TP_ITEMS_LOT_CNAB_PAYMENT') IS NOT NULL DROP TYPE [TP_ITEMS_LOT_CNAB_PAYMENT];
GO
IF OBJECT_ID('SP_LS_LOTS_CNAB_TO_PROCESS') IS NOT NULL DROP PROCEDURE SP_LS_LOTS_CNAB_TO_PROCESS
GO
IF OBJECT_ID('SP_FD_CNAB_TO_RETENTATIVE') IS NOT NULL DROP PROCEDURE SP_FD_CNAB_TO_RETENTATIVE
GO
IF OBJECT_ID('SP_UP_ITEMS_CNAB_LOT') IS NOT NULL DROP PROCEDURE SP_UP_ITEMS_CNAB_LOT;
GO
IF OBJECT_ID('SP_LS_LOT_TO_RETRY') IS NOT NULL DROP PROCEDURE SP_LS_LOT_TO_RETRY;
GO
IF OBJECT_ID('SP_LOT_CNAB_DETAIL') IS NOT NULL DROP PROCEDURE SP_LOT_CNAB_DETAIL;
GO
IF OBJECT_ID('SP_LS_ITEMS_LOT_CNAB') IS NOT NULL DROP PROCEDURE SP_LS_ITEMS_LOT_CNAB;
GO
IF OBJECT_ID('VW_PROTOCOLS_FINANCE_SCHEDULE_FILE') IS NOT NULL DROP VIEW VW_PROTOCOLS_FINANCE_SCHEDULE_FILE;
GO
IF OBJECT_ID('SP_REG_CNAB_FILE_LOT') IS NOT NULL DROP PROCEDURE SP_REG_CNAB_FILE_LOT;
GO
IF OBJECT_ID('SP_REG_NOTIFICATION_MESSAGES') IS NOT NULL DROP PROCEDURE SP_REG_NOTIFICATION_MESSAGES;
GO
IF OBJECT_ID('SP_LS_NOTIFY_MESSAGES') IS NOT NULL DROP PROCEDURE SP_LS_NOTIFY_MESSAGES
GO
IF OBJECT_ID('SP_LS_READED_NOTIFY_MESSAGES') IS NOT NULL DROP PROCEDURE SP_LS_READED_NOTIFY_MESSAGES
GO
IF OBJECT_ID('SP_REP_CNAB_PAYMENTS') IS NOT NULL DROP PROCEDURE SP_REP_CNAB_PAYMENTS
CREATE TYPE [TP_ITEMS_LOT_CNAB_PAYMENT] AS TABLE
(

[COD_FIN_SCH_FILE] INT,
[VALUE_PAYMENT] DECIMAL(22, 8),
[FILE_SEQUENCE] VARCHAR(255),
[COD_EC] INT,
[CNPJ_EC] VARCHAR(255),
[EC_NAME] VARCHAR(255),
[AFFILIATOR] VARCHAR(255),
[CNPJ_AFF] VARCHAR(255),
[PAYMENT_DATE] DATETIME,
[CNAB_SIT] VARCHAR(255),
[COD_SITUATION] INT,
[SITUATION_TR] VARCHAR(200)
);

CREATE TABLE CNAB_FILE_LOT 
(
	COD_CNAB_FILE_LOT INT PRIMARY KEY IDENTITY(1,1),
	CREATED_AT DATETIME,
	COD_USER INT FOREIGN KEY REFERENCES USERS (COD_USER),
	COD_SITUATION INT FOREIGN KEY REFERENCES SITUATION (COD_SITUATION),
	END_DATE DATETIME	 
);

GO

CREATE TABLE [LOT_CNAB_PAYMENT] (
  [COD_LOT_PAY] int PRIMARY KEY IDENTITY(1, 1),
  [CREATED_AT] datetime,
  [COD_CNAB_FILE_LOT] INT FOREIGN KEY REFERENCES CNAB_FILE_LOT (COD_CNAB_FILE_LOT),
  [TYPE_BANK] INT,
  [COD_USER] INT,
  [COD_SITUATION] INT,
  [ALTER_DATE] datetime,
  READED INT DEFAULT 0
)
GO
CREATE TABLE [ITEMS_LOT_CNAB_PAYMENT] (
  [COD_ITEM_LOT] INT PRIMARY KEY IDENTITY(1, 1),
  [CREATED_AT] DATETIME,
  [COD_LOT_PAY] int,
  [COD_FIN_SCH_FILE] INT,
  [COD_CNAB_OC] INT,
  [FILE_SEQUENCE] VARCHAR(250),
  [VALUE_PAYMENT] decimal(22,8),
  [SEQUENCE_FILENAME] VARCHAR(255),
  [COD_EC] int,
  [CNPJ_EC] VARCHAR(255),
  [EC_NAME] VARCHAR(255),
  [AFFILIATOR] VARCHAR(255),
  [CNPJ_AFF] VARCHAR(255),
  [PAYMENT_DATE] datetime,
  [COD_SITUATION] INT,
  [SITUATION_TR] VARCHAR(200)
)
GO

CREATE TABLE [CNAB_OCCURRENCES] (
  [COD_CNAB_OC] INT PRIMARY KEY IDENTITY(1, 1),
  [CODE] VARCHAR(150),
  [DESCRIPTION] VARCHAR(300),
  [TYPE_BANK] VARCHAR(100)
)
GO

ALTER TABLE [ITEMS_LOT_CNAB_PAYMENT] ADD FOREIGN KEY ([COD_LOT_PAY]) REFERENCES [LOT_CNAB_PAYMENT] ([COD_LOT_PAY])
GO

ALTER TABLE [ITEMS_LOT_CNAB_PAYMENT] ADD FOREIGN KEY ([COD_FIN_SCH_FILE]) REFERENCES [FINANCE_SCHEDULE_FILE] ([COD_FIN_SCH_FILE])
GO

ALTER TABLE [ITEMS_LOT_CNAB_PAYMENT] ADD FOREIGN KEY ([COD_CNAB_OC]) REFERENCES [CNAB_OCCURRENCES] ([COD_CNAB_OC])
GO


ALTER TABLE [LOT_CNAB_PAYMENT] ADD FOREIGN KEY (COD_USER) REFERENCES USERS (COD_USER)
GO

CREATE PROCEDURE SP_REG_CNAB_FILE_LOT
(
	@COD_USER INT
)
AS
BEGIN

INSERT INTO CNAB_FILE_LOT (CREATED_AT, COD_USER, COD_SITUATION)
	VALUES (current_timestamp, @COD_USER, (SELECT SITUATION.COD_SITUATION FROM SITUATION INNER JOIN TRADUCTION_SITUATION ON SITUATION.COD_SITUATION = TRADUCTION_SITUATION.COD_SITUATION WHERE NAME = 'AWAITING PROCESSING'));
IF @@rowcount < 1
THROW 60002, '75000', 1;

SELECT
	*
FROM CNAB_FILE_LOT
WHERE COD_CNAB_FILE_LOT = SCOPE_IDENTITY()

END;
GO
CREATE PROCEDURE SP_REG_ITEMS_LOT_CNAB_PAYMENT 
(
	@TP_ITEMS_LOT_CNAB_PAYMENT [TP_ITEMS_LOT_CNAB_PAYMENT] READONLY,
	@COD_USER INT,
	@TYPEBANK INT,
	@COD_CNAB_FILE INT
)
AS

DECLARE @COD_SITUATION INT;
DECLARE @SIT_TR VARCHAR(100);

BEGIN

SELECT
	@COD_SITUATION = SITUATION.COD_SITUATION
   ,@SIT_TR = TRADUCTION_SITUATION.SITUATION_TR
FROM SITUATION
INNER JOIN TRADUCTION_SITUATION
	ON SITUATION.COD_SITUATION = TRADUCTION_SITUATION.COD_SITUATION
WHERE NAME = 'AWAITING PROCESSING'

INSERT INTO [LOT_CNAB_PAYMENT] (CREATED_AT,
COD_USER,
COD_SITUATION,
TYPE_BANK,
COD_CNAB_FILE_LOT)
	VALUES (current_timestamp, @COD_USER, @COD_SITUATION, 161 , @COD_CNAB_FILE)

DECLARE @LOT_CODE INT = SCOPE_IDENTITY();




INSERT INTO ITEMS_LOT_CNAB_PAYMENT (COD_LOT_PAY,
CREATED_AT,
COD_FIN_SCH_FILE,
VALUE_PAYMENT,
FILE_SEQUENCE,
COD_EC,
CNPJ_EC,
EC_NAME,
AFFILIATOR,
CNPJ_AFF,
PAYMENT_DATE,
COD_CNAB_OC,
COD_SITUATION,
SITUATION_TR)
	SELECT
		@LOT_CODE
	   ,current_timestamp
	   ,COD_FIN_SCH_FILE
	   ,VALUE_PAYMENT
	   ,FILE_SEQUENCE
	   ,COD_EC
	   ,CNPJ_EC
	   ,EC_NAME
	   ,AFFILIATOR
	   ,CNPJ_AFF
	   ,PAYMENT_DATE
	   ,(SELECT
				COD_CNAB_OC
			FROM CNAB_OCCURRENCES
			WHERE CODE = TP.CNAB_SIT)
	   ,@COD_SITUATION
	   ,@SIT_TR
	FROM @TP_ITEMS_LOT_CNAB_PAYMENT AS TP

END;
GO


GO
CREATE PROCEDURE [dbo].[SP_FD_SCHEDULE_FILE]    
(  
 @FILE_CODE [CODE_UQ_TYPE] READONLY,    
 @SHIPPING_BANK INT  
)       
AS       
BEGIN

SELECT
	FINANCE_SCHEDULE_FILE.COD_FIN_SCH_FILE
   ,FINANCE_SCHEDULE_FILE.AMOUNT
   ,FINANCE_SCHEDULE_FILE.FILE_SEQUENCE
   ,FINANCE_SCHEDULE_FILE.MODIFY_DATE
   ,FINANCE_SCHEDULE_FILE.COD_SITUATION
   ,TRADUCTION_SITUATION.SITUATION_TR
   ,COMMERCIAL_ESTABLISHMENT.COD_EC
   ,COMMERCIAL_ESTABLISHMENT.CPF_CNPJ
   ,COMMERCIAL_ESTABLISHMENT.NAME AS EC_NAME
   ,AFFILIATOR.NAME
   ,AFFILIATOR.CPF_CNPJ AS AFF_CNPJ
   ,FINANCE_SCHEDULE_FILE.[file_name]
   ,FINANCE_SCHEDULE_FILE.SEARCH_DATE
   ,ITEMS_LOT_CNAB_PAYMENT.PAYMENT_DATE
FROM @FILE_CODE FILE_CODE
JOIN FINANCE_SCHEDULE_FILE
	ON FILE_SEQUENCE = FILE_CODE.CODE
JOIN BANK_DETAILS_EC
	ON BANK_DETAILS_EC.COD_BK_EC = FINANCE_SCHEDULE_FILE.COD_BK_EC
JOIN COMMERCIAL_ESTABLISHMENT
	ON COMMERCIAL_ESTABLISHMENT.COD_EC = BANK_DETAILS_EC.COD_EC
LEFT JOIN AFFILIATOR
	ON AFFILIATOR.COD_AFFILIATOR = COMMERCIAL_ESTABLISHMENT.COD_AFFILIATOR
LEFT JOIN TRADUCTION_SITUATION
	ON TRADUCTION_SITUATION.COD_SITUATION = FINANCE_SCHEDULE_FILE.COD_SITUATION
LEFT JOIN ITEMS_LOT_CNAB_PAYMENT
	ON ITEMS_LOT_CNAB_PAYMENT.COD_FIN_SCH_FILE = FINANCE_SCHEDULE_FILE.COD_FIN_SCH_FILE
WHERE FINANCE_SCHEDULE_FILE.TYPE_BANK = @SHIPPING_BANK
AND ITEMS_LOT_CNAB_PAYMENT.COD_FIN_SCH_FILE IS NULL
;

END;

GO

CREATE PROCEDURE SP_LS_LOTS_CNAB_TO_PROCESS
AS
BEGIN
DECLARE @COD_SIT INT;

SELECT
	@COD_SIT = COD_SITUATION
FROM SITUATION
WHERE NAME = 'AWAITING PROCESSING'

SELECT
	LOT_CNAB_PAYMENT.COD_LOT_PAY
   ,ITEMS_LOT_CNAB_PAYMENT.FILE_SEQUENCE
   ,CNAB_OCCURRENCES.CODE
   ,LOT_CNAB_PAYMENT.TYPE_BANK
FROM LOT_CNAB_PAYMENT
INNER JOIN ITEMS_LOT_CNAB_PAYMENT
	ON ITEMS_LOT_CNAB_PAYMENT.COD_LOT_PAY = LOT_CNAB_PAYMENT.COD_LOT_PAY
INNER JOIN CNAB_OCCURRENCES
	ON CNAB_OCCURRENCES.COD_CNAB_OC = ITEMS_LOT_CNAB_PAYMENT.COD_CNAB_OC
WHERE LOT_CNAB_PAYMENT.COD_SITUATION = @COD_SIT
AND ITEMS_LOT_CNAB_PAYMENT.SITUATION_TR = 'AWAITING PROCESSING'
AND LOT_CNAB_PAYMENT.COD_LOT_PAY = (SELECT TOP 1
		COD_LOT_PAY
	FROM LOT_CNAB_PAYMENT
	WHERE COD_SITUATION = 31)
END

GO

CREATE PROCEDURE SP_UP_ITEMS_CNAB_LOT        
(        
 @SEQUENCES CODE_TYPE READONLY,    
 @SITUATION VARCHAR(150)    
)        
AS        
BEGIN
  
    
    
DECLARE @COD_SIT INT = ( SELECT
		COD_SITUATION
	FROM SITUATION
	WHERE NAME = @SITUATION);
DECLARE @COD_LOT INT = (SELECT
		COD_LOT_PAY
	FROM ITEMS_LOT_CNAB_PAYMENT
	WHERE FILE_SEQUENCE = (SELECT
		TOP 1
			*
		FROM @SEQUENCES));
DECLARE @COD_CNAB_FILE INT = (SELECT
		COD_CNAB_FILE_LOT
	FROM LOT_CNAB_PAYMENT
	WHERE COD_LOT_PAY = @COD_LOT);

UPDATE ITEMS_LOT_CNAB_PAYMENT
SET COD_SITUATION = (SELECT
			COD_SITUATION
		FROM SITUATION
		WHERE COD_SITUATION = @COD_SIT)
   ,SITUATION_TR = (SELECT
			SITUATION_TR
		FROM TRADUCTION_SITUATION
		WHERE COD_SITUATION = (SELECT
				COD_SITUATION
			FROM SITUATION
			WHERE COD_SITUATION = @COD_SIT))
FROM ITEMS_LOT_CNAB_PAYMENT
WHERE FILE_SEQUENCE IN (SELECT
		*
	FROM @SEQUENCES)

IF (SELECT
			COUNT(*)
		FROM ITEMS_LOT_CNAB_PAYMENT
		WHERE COD_LOT_PAY = @COD_LOT
		AND COD_SITUATION <> (SELECT
				COD_SITUATION
			FROM SITUATION
			WHERE NAME = 'PAYMENT PROCESSED'))
	= 0
BEGIN
UPDATE LOT_CNAB_PAYMENT
SET COD_SITUATION = @COD_SIT
   ,ALTER_DATE = current_timestamp
WHERE COD_LOT_PAY = @COD_LOT;
END

IF (SELECT
			COUNT(*)
		FROM LOT_CNAB_PAYMENT
		WHERE COD_CNAB_FILE_LOT = @COD_CNAB_FILE
		AND COD_SITUATION <> (SELECT
				COD_SITUATION
			FROM SITUATION
			WHERE NAME = 'PAYMENT PROCESSED'))
	= 0
BEGIN
UPDATE CNAB_FILE_LOT
SET COD_SITUATION = (SELECT
			COD_SITUATION
		FROM SITUATION
		WHERE NAME = 'PAYMENT PROCESSED')
   ,END_DATE = current_timestamp
WHERE COD_CNAB_FILE_LOT = @COD_CNAB_FILE;


SELECT
	CNAB_FILE_LOT.CREATED_AT
   ,CNAB_FILE_LOT.END_DATE
   ,SOURCE_PROCESS.COD_SOURCE_PROCESS COD_SOURCE
   ,SOURCE_PROCESS.CODE AS SOURCE_DESC
   ,USERS.COD_USER
   ,CNAB_FILE_LOT.COD_CNAB_FILE_LOT
FROM CNAB_FILE_LOT
INNER JOIN USERS
	ON USERS.COD_PROFILE = 17
INNER JOIN SOURCE_PROCESS
	ON SOURCE_PROCESS.DESCRIPTION = 'PROCESS_CNAB_PAYMENT'
		AND CNAB_FILE_LOT.COD_CNAB_FILE_LOT = @COD_CNAB_FILE

END;
END
GO

GO

    
CREATE PROCEDURE SP_LS_LOT_TO_RETRY  
AS  
BEGIN
SELECT DISTINCT
	LOT_CNAB_PAYMENT.COD_LOT_PAY
   ,LOT_CNAB_PAYMENT.CREATED_AT
   ,LOT_CNAB_PAYMENT.TYPE_BANK
   ,LOT_CNAB_PAYMENT.COD_USER
   ,LOT_CNAB_PAYMENT.COD_SITUATION
FROM LOT_CNAB_PAYMENT
INNER JOIN ITEMS_LOT_CNAB_PAYMENT
	ON ITEMS_LOT_CNAB_PAYMENT.COD_LOT_PAY = LOT_CNAB_PAYMENT.COD_LOT_PAY
INNER JOIN SITUATION
	ON SITUATION.COD_SITUATION = ITEMS_LOT_CNAB_PAYMENT.COD_SITUATION
WHERE SITUATION.NAME = 'AWAITING RETENTATIVE'
END

GO
  
CREATE PROCEDURE SP_FD_CNAB_TO_RETENTATIVE      
(
	@COD_LOT_PAY INT
)
AS      
BEGIN
SELECT
	FINANCE_SCHEDULE_FILE.COD_FIN_SCH_FILE
   ,FINANCE_SCHEDULE_FILE.AMOUNT
   ,FINANCE_SCHEDULE_FILE.FILE_SEQUENCE
   ,FINANCE_SCHEDULE_FILE.MODIFY_DATE
   ,FINANCE_SCHEDULE_FILE.COD_SITUATION
   ,TRADUCTION_SITUATION.SITUATION_TR
   ,COMMERCIAL_ESTABLISHMENT.COD_EC
   ,COMMERCIAL_ESTABLISHMENT.CPF_CNPJ
   ,COMMERCIAL_ESTABLISHMENT.NAME AS EC_NAME
   ,AFFILIATOR.NAME
   ,AFFILIATOR.CPF_CNPJ AS AFF_CNPJ
   ,FINANCE_SCHEDULE_FILE.[file_name]
   ,FINANCE_SCHEDULE_FILE.SEARCH_DATE
   ,FINANCE_SCHEDULE_FILE.TYPE_BANK
   ,ITEMS_LOT_CNAB_PAYMENT.COD_LOT_PAY
   ,FINANCE_SCHEDULE_FILE.TYPE_BANK
   ,FINANCE_SCHEDULE_FILE.COD_USER_CREAT
   ,CNAB_OCCURRENCES.CODE AS CNAB_SIT
   ,ITEMS_LOT_CNAB_PAYMENT.PAYMENT_DATE
FROM ITEMS_LOT_CNAB_PAYMENT
JOIN FINANCE_SCHEDULE_FILE
	ON FINANCE_SCHEDULE_FILE.FILE_SEQUENCE = ITEMS_LOT_CNAB_PAYMENT.FILE_SEQUENCE
JOIN BANK_DETAILS_EC
	ON BANK_DETAILS_EC.COD_BK_EC = FINANCE_SCHEDULE_FILE.COD_BK_EC
JOIN COMMERCIAL_ESTABLISHMENT
	ON COMMERCIAL_ESTABLISHMENT.COD_EC = BANK_DETAILS_EC.COD_EC
LEFT JOIN AFFILIATOR
	ON AFFILIATOR.COD_AFFILIATOR = COMMERCIAL_ESTABLISHMENT.COD_AFFILIATOR
LEFT JOIN TRADUCTION_SITUATION
	ON TRADUCTION_SITUATION.COD_SITUATION = FINANCE_SCHEDULE_FILE.COD_SITUATION
INNER JOIN SITUATION
	ON SITUATION.COD_SITUATION = ITEMS_LOT_CNAB_PAYMENT.COD_SITUATION
INNER JOIN CNAB_OCCURRENCES
	ON CNAB_OCCURRENCES.COD_CNAB_OC = ITEMS_LOT_CNAB_PAYMENT.COD_CNAB_OC
WHERE SITUATION.NAME = 'AWAITING RETENTATIVE'
AND COD_LOT_PAY = @COD_LOT_PAY
END

GO
CREATE PROCEDURE SP_LOT_CNAB_DETAIL
(
	@COD_FILE INT
) AS
BEGIN
SELECT
	COUNT(DISTINCT LOT_CNAB_PAYMENT.COD_LOT_PAY) AS LOT_AMOUNT
   ,CAST(CNAB_FILE_LOT.CREATED_AT AS DATE) AS CNAB_DATE
   ,USERS.IDENTIFICATION AS USERNAME
   ,CAST(CNAB_FILE_LOT.END_DATE AS DATE) AS PAYMENT_DATE
   ,COUNT(CAST(ITEMS_LOT_CNAB_PAYMENT.CREATED_AT AS DATE)) AS QTY_PAYMENTS
   ,SUM(ITEMS_LOT_CNAB_PAYMENT.VALUE_PAYMENT) AS AMOUNT
FROM CNAB_FILE_LOT
INNER JOIN LOT_CNAB_PAYMENT
	ON LOT_CNAB_PAYMENT.COD_CNAB_FILE_LOT = CNAB_FILE_LOT.COD_CNAB_FILE_LOT
INNER JOIN USERS
	ON USERS.COD_USER = LOT_CNAB_PAYMENT.COD_USER
INNER JOIN ITEMS_LOT_CNAB_PAYMENT
	ON ITEMS_LOT_CNAB_PAYMENT.COD_LOT_PAY = LOT_CNAB_PAYMENT.COD_LOT_PAY
INNER JOIN BANKS
	ON BANKS.COD_BANK = LOT_CNAB_PAYMENT.TYPE_BANK
WHERE LOT_CNAB_PAYMENT.COD_SITUATION = (SELECT
		COD_SITUATION
	FROM SITUATION
	WHERE NAME = 'PAYMENT PROCESSED')
AND CNAB_FILE_LOT.COD_CNAB_FILE_LOT = @COD_FILE
GROUP BY
--LOT_CNAB_PAYMENT.COD_LOT_PAY
 USERS.IDENTIFICATION
,CNAB_FILE_LOT.CREATED_AT
,CNAB_FILE_LOT.END_DATE
--,ITEMS_LOT_CNAB_PAYMENT.COD_ITEM_LOT
--,ITEMS_LOT_CNAB_PAYMENT.VALUE_PAYMENT
END

GO

CREATE  VIEW VW_PROTOCOLS_FINANCE_SCHEDULE_FILE
AS
SELECT
	PROTOCOLS.PROTOCOL
   ,FINANCE_SCHEDULE_FILE.COD_FIN_SCH_FILE
FROM TRANSACTION_TITLES WITH(NOLOCK)
INNER JOIN PROTOCOLS WITH(NOLOCK)
	ON PROTOCOLS.COD_PAY_PROT = TRANSACTION_TITLES.COD_PAY_PROT
INNER JOIN FINANCE_SCHEDULE_FILE
	ON FINANCE_SCHEDULE_FILE.COD_FIN_SCH_FILE = TRANSACTION_TITLES.COD_FIN_SCH_FILE
WHERE TRANSACTION_TITLES.COD_SITUATION = 8
UNION
SELECT
	PROTOCOLS.PROTOCOL
   ,FINANCE_SCHEDULE_FILE.COD_FIN_SCH_FILE
FROM RELEASE_ADJUSTMENTS WITH(NOLOCK)
INNER JOIN PROTOCOLS WITH(NOLOCK)
	ON PROTOCOLS.COD_PAY_PROT = RELEASE_ADJUSTMENTS.COD_PAY_PROT
INNER JOIN FINANCE_SCHEDULE_FILE
	ON FINANCE_SCHEDULE_FILE.COD_FIN_SCH_FILE = RELEASE_ADJUSTMENTS.COD_FIN_SCH_FILE
WHERE RELEASE_ADJUSTMENTS.COD_SITUATION = 8
UNION
SELECT
	PROTOCOLS.PROTOCOL
   ,FINANCE_SCHEDULE_FILE.COD_FIN_SCH_FILE
FROM TARIFF_EC WITH(NOLOCK)
INNER JOIN PROTOCOLS WITH(NOLOCK)
	ON PROTOCOLS.COD_PAY_PROT = TARIFF_EC.COD_PAY_PROT
INNER JOIN FINANCE_SCHEDULE_FILE
	ON FINANCE_SCHEDULE_FILE.COD_FIN_SCH_FILE = TARIFF_EC.COD_FIN_SCH_FILE
WHERE TARIFF_EC.COD_SITUATION = 8
UNION
SELECT
	PROTOCOLS.PROTOCOL
   ,FINANCE_SCHEDULE_FILE.COD_FIN_SCH_FILE
FROM TITLE_LOCK_PAYMENT_DETAILS WITH(NOLOCK)
INNER JOIN PROTOCOLS WITH(NOLOCK)
	ON PROTOCOLS.COD_PAY_PROT = TITLE_LOCK_PAYMENT_DETAILS.COD_PAY_PROT
INNER JOIN FINANCE_SCHEDULE_FILE
	ON FINANCE_SCHEDULE_FILE.COD_FIN_SCH_FILE = TITLE_LOCK_PAYMENT_DETAILS.COD_FIN_SCH_FILE
WHERE TITLE_LOCK_PAYMENT_DETAILS.COD_SITUATION = 8

GO
CREATE PROCEDURE SP_LS_ITEMS_LOT_CNAB  
(  
 @COD_LOT INT
)  
AS  
BEGIN

SELECT
	ITEMS_LOT_CNAB_PAYMENT.EC_NAME
   ,ITEMS_LOT_CNAB_PAYMENT.CNPJ_EC
   ,ITEMS_LOT_CNAB_PAYMENT.VALUE_PAYMENT
   ,ITEMS_LOT_CNAB_PAYMENT.PAYMENT_DATE
   ,CNAB_OCCURRENCES.CODE + ' - ' +
	CNAB_OCCURRENCES.DESCRIPTION AS 'CNAB_SITUATION'
   ,VW_PROTOCOLS_FINANCE_SCHEDULE_FILE.PROTOCOL
FROM ITEMS_LOT_CNAB_PAYMENT
INNER JOIN CNAB_OCCURRENCES
	ON CNAB_OCCURRENCES.COD_CNAB_OC = ITEMS_LOT_CNAB_PAYMENT.COD_CNAB_OC
INNER JOIN FINANCE_SCHEDULE_FILE
	ON FINANCE_SCHEDULE_FILE.COD_FIN_SCH_FILE = ITEMS_LOT_CNAB_PAYMENT.COD_FIN_SCH_FILE
LEFT JOIN VW_PROTOCOLS_FINANCE_SCHEDULE_FILE
	ON VW_PROTOCOLS_FINANCE_SCHEDULE_FILE.COD_FIN_SCH_FILE = FINANCE_SCHEDULE_FILE.COD_FIN_SCH_FILE
INNER JOIN LOT_CNAB_PAYMENT
	ON LOT_CNAB_PAYMENT.COD_LOT_PAY = ITEMS_LOT_CNAB_PAYMENT.COD_LOT_PAY
WHERE LOT_CNAB_PAYMENT.COD_CNAB_FILE_LOT = @COD_LOT

END;

GO

CREATE PROCEDURE [dbo].[SP_REG_NOTIFICATION_MESSAGES]                    
(                    
 @COD_USER INT,                    
 @CONTENT_MESSAGE VARCHAR(300),                    
 @LINK_REPORT VARCHAR(400) = NULL,                    
 @COD_SOURCE_PROCESS INT                    
)                    
AS                    
BEGIN
        
IF (@COD_SOURCE_PROCESS = ( SELECT
		COD_SOURCE_PROCESS
	FROM SOURCE_PROCESS
	WHERE DESCRIPTION = 'PROCESS_CNAB_PAYMENT')
)
BEGIN

INSERT INTO NOTIFICATION_MESSAGES (COD_USER,
CREATED_AT,
CONTENT_MESSAGE,
LINK_REPORT,
COD_SOURCE_PROCESS,
NOTIFY_READ,
CODE,
GENERATE_STATUS)
	VALUES (@COD_USER, current_timestamp, @CONTENT_MESSAGE, @LINK_REPORT, @COD_SOURCE_PROCESS, 0, NEXT VALUE FOR SEQ_REP_EXP, 'Concluído');

SELECT
	COD_NOTIFY_MESSAGE
   ,COD_USER
   ,CREATED_AT
   ,EXPIRED
   ,CONTENT_MESSAGE
   ,LINK_REPORT
   ,COD_SOURCE_PROCESS
   ,NOTIFY_READ
   ,CODE
FROM NOTIFICATION_MESSAGES
WHERE COD_NOTIFY_MESSAGE = SCOPE_IDENTITY();

END
ELSE
BEGIN
INSERT INTO NOTIFICATION_MESSAGES (COD_USER,
CREATED_AT,
CONTENT_MESSAGE,
LINK_REPORT,
COD_SOURCE_PROCESS,
NOTIFY_READ,
CODE,
GENERATE_STATUS)
	VALUES (@COD_USER, current_timestamp, @CONTENT_MESSAGE, @LINK_REPORT, @COD_SOURCE_PROCESS, 0, NEXT VALUE FOR SEQ_REP_EXP, 'Na fila para processamento');

SELECT
	COD_NOTIFY_MESSAGE
   ,COD_USER
   ,CREATED_AT
   ,EXPIRED
   ,CONTENT_MESSAGE
   ,LINK_REPORT
   ,COD_SOURCE_PROCESS
   ,NOTIFY_READ
   ,CODE
FROM NOTIFICATION_MESSAGES
WHERE COD_NOTIFY_MESSAGE = SCOPE_IDENTITY();
END
END;


CREATE PROCEDURE SP_LS_READED_NOTIFY_MESSAGES (@COD_USER INT)
AS
BEGIN

DELETE FROM NOTIFICATION_MESSAGES
WHERE DATEDIFF(DAY, NOTIFICATION_MESSAGES.CREATED_AT, current_timestamp) > 1;

WITH CTE
AS
(SELECT
	TOP 15
		NOTIFICATION_MESSAGES.COD_NOTIFY_MESSAGE
	   ,NOTIFICATION_MESSAGES.COD_USER
	   ,dbo.FN_FUS_UTF(NOTIFICATION_MESSAGES.CREATED_AT) AS CREATED_AT
	   ,NOTIFICATION_MESSAGES.EXPIRED
	   ,NOTIFICATION_MESSAGES.CONTENT_MESSAGE
	   ,NOTIFICATION_MESSAGES.LINK_REPORT
	   ,NOTIFICATION_MESSAGES.COD_SOURCE_PROCESS
	   ,NOTIFICATION_MESSAGES.NOTIFY_READ
	   ,NOTIFICATION_MESSAGES.CODE
	   ,NOTIFICATION_MESSAGES.NOTIFY_SENT
	   ,SOURCE_PROCESS.CODE AS REPORT_NAME
	   ,SOURCE_PROCESS.DESCRIPTION
	   ,NOTIFICATION_MESSAGES.GENERATE_STATUS
	FROM NOTIFICATION_MESSAGES
	INNER JOIN SOURCE_PROCESS
		ON SOURCE_PROCESS.COD_SOURCE_PROCESS = NOTIFICATION_MESSAGES.COD_SOURCE_PROCESS
	WHERE COD_USER = @COD_USER
	--AND NOTIFY_SENT = 1      
	ORDER BY 1 DESC)
SELECT
	*
FROM CTE
ORDER BY 1 ASC;

END;

GO

CREATE PROCEDURE SP_LS_NOTIFY_MESSAGES (@COD_USER INT)
AS
BEGIN

SELECT
	NOTIFICATION_MESSAGES.COD_NOTIFY_MESSAGE
   ,NOTIFICATION_MESSAGES.COD_USER
   ,NOTIFICATION_MESSAGES.CREATED_AT
   ,NOTIFICATION_MESSAGES.EXPIRED
   ,NOTIFICATION_MESSAGES.CONTENT_MESSAGE
   ,NOTIFICATION_MESSAGES.LINK_REPORT
   ,NOTIFICATION_MESSAGES.COD_SOURCE_PROCESS
   ,NOTIFICATION_MESSAGES.NOTIFY_READ
   ,NOTIFICATION_MESSAGES.CODE
   ,NOTIFICATION_MESSAGES.GENERATE_STATUS
   ,SOURCE_PROCESS.DESCRIPTION
FROM NOTIFICATION_MESSAGES
INNER JOIN SOURCE_PROCESS
	ON SOURCE_PROCESS.COD_SOURCE_PROCESS = NOTIFICATION_MESSAGES.COD_SOURCE_PROCESS
		--WHERE COD_USER = @COD_USER
		--AND NOTIFY_READ = 0
		AND GENERATE_STATUS = 'Concluído'

END;

GO

IF (SELECT
			COUNT(*)
		FROM CNAB_OCCURRENCES)
	= 0
BEGIN
INSERT INTO CNAB_OCCURRENCES (CODE, DESCRIPTION)
	VALUES ('OK', 'PAGAMENTO EFETUADO')
INSERT INTO CNAB_OCCURRENCES (CODE, DESCRIPTION)
	VALUES ('AE', 'DATA DE PAGAMENTO ALTERADA')
INSERT INTO CNAB_OCCURRENCES (CODE, DESCRIPTION)
	VALUES ('AG', 'NÚMERO DO LOTE INVÁLIDO')
INSERT INTO CNAB_OCCURRENCES (CODE, DESCRIPTION)
	VALUES ('AH', 'NÚMERO SEQUENCIAL DO REGISTRO NO LOTE INVÁLIDO')
INSERT INTO CNAB_OCCURRENCES (CODE, DESCRIPTION)
	VALUES ('AI', 'PRODUTO DEMONSTRATIVO DE PAGAMENTO NÃO CONTRATADO')
INSERT INTO CNAB_OCCURRENCES (CODE, DESCRIPTION)
	VALUES ('AJ', 'TIPO DE MOVIMENTO INVÁLIDO')
INSERT INTO CNAB_OCCURRENCES (CODE, DESCRIPTION)
	VALUES ('AL', 'CÓDIGO DO BANCO FAVORECIDO INVÁLIDO')
INSERT INTO CNAB_OCCURRENCES (CODE, DESCRIPTION)
	VALUES ('AM', 'AGÊNCIA DO FAVORECIDO INVÁLIDA')
INSERT INTO CNAB_OCCURRENCES (CODE, DESCRIPTION)
	VALUES ('AN', 'CONTA CORRENTE DO FAVORECIDO INVÁLIDA / CONTA INVESTIMENTO EXTINTA')
INSERT INTO CNAB_OCCURRENCES (CODE, DESCRIPTION)
	VALUES ('EM', '30/04/2011')
INSERT INTO CNAB_OCCURRENCES (CODE, DESCRIPTION)
	VALUES ('AO', 'NOME DO FAVORECIDO INVÁLIDO')
INSERT INTO CNAB_OCCURRENCES (CODE, DESCRIPTION)
	VALUES ('AP', 'DATA DE PAGAMENTO / DATA DE VALIDADE / HORA DE LANÇAMENTO /ARRECADAÇÃO / APURAÇÃO INVÁLIDA')
INSERT INTO CNAB_OCCURRENCES (CODE, DESCRIPTION)
	VALUES ('AQ', 'QUANTIDADE DE REGISTROS MAIOR QUE 999999')
INSERT INTO CNAB_OCCURRENCES (CODE, DESCRIPTION)
	VALUES ('AR', 'VALOR ARRECADADO / LANÇAMENTO INVÁLIDO')
INSERT INTO CNAB_OCCURRENCES (CODE, DESCRIPTION)
	VALUES ('BC', 'NOSSO NÚMERO INVÁLIDO')
INSERT INTO CNAB_OCCURRENCES (CODE, DESCRIPTION)
	VALUES ('BD', 'PAGAMENTO AGENDADO')
INSERT INTO CNAB_OCCURRENCES (CODE, DESCRIPTION)
	VALUES ('BE', 'PAGAMENTO AGENDADO COM FORMA ALTERADA PARA OP')
INSERT INTO CNAB_OCCURRENCES (CODE, DESCRIPTION)
	VALUES ('BI', 'CNPJ / CPF DO FAVORECIDO NO SEGMENTOJ-52 ou B INVÁLIDO')
INSERT INTO CNAB_OCCURRENCES (CODE, DESCRIPTION)
	VALUES ('BL', 'VALOR DA PARCELA INVÁLIDO')
INSERT INTO CNAB_OCCURRENCES (CODE, DESCRIPTION)
	VALUES ('CD', 'CNPJ / CPF INFORMADO DIVERGENTE DO CADASTRADO')
INSERT INTO CNAB_OCCURRENCES (CODE, DESCRIPTION)
	VALUES ('CE', 'PAGAMENTO CANCELADO')
INSERT INTO CNAB_OCCURRENCES (CODE, DESCRIPTION)
	VALUES ('CF', 'VALOR DO DOCUMENTO INVÁLIDO')
INSERT INTO CNAB_OCCURRENCES (CODE, DESCRIPTION)
	VALUES ('CG', 'VALOR DO ABATIMENTO INVÁLIDO')
INSERT INTO CNAB_OCCURRENCES (CODE, DESCRIPTION)
	VALUES ('CH', 'VALOR DO DESCONTO INVÁLIDO')
INSERT INTO CNAB_OCCURRENCES (CODE, DESCRIPTION)
	VALUES ('CI', 'CNPJ / CPF / IDENTIFICADOR / INSCRIÇÃO ESTADUAL / INSCRIÇÃO NO CAD / ICMS')
INSERT INTO CNAB_OCCURRENCES (CODE, DESCRIPTION)
	VALUES ('IN', 'VÁLIDO')
INSERT INTO CNAB_OCCURRENCES (CODE, DESCRIPTION)
	VALUES ('CJ', 'VALOR DA MULTA INVÁLIDO')
INSERT INTO CNAB_OCCURRENCES (CODE, DESCRIPTION)
	VALUES ('CK', 'TIPO DE INSCRIÇÃO INVÁLIDA')
INSERT INTO CNAB_OCCURRENCES (CODE, DESCRIPTION)
	VALUES ('CL', 'VALOR DO INSS INVÁLIDO')
INSERT INTO CNAB_OCCURRENCES (CODE, DESCRIPTION)
	VALUES ('CM', 'VALOR DO COFINS INVÁLIDO')
INSERT INTO CNAB_OCCURRENCES (CODE, DESCRIPTION)
	VALUES ('CN', 'CONTA NÃO CADASTRADA')
INSERT INTO CNAB_OCCURRENCES (CODE, DESCRIPTION)
	VALUES ('CO', 'VALOR DE OUTRAS ENTIDADES INVÁLIDO')
INSERT INTO CNAB_OCCURRENCES (CODE, DESCRIPTION)
	VALUES ('B', 'CP CONFIRMAÇÃO DE OP CUMPRIDA')
INSERT INTO CNAB_OCCURRENCES (CODE, DESCRIPTION)
	VALUES ('CQ', 'SOMA DAS FATURAS DIFERE DO PAGAMENTO')
INSERT INTO CNAB_OCCURRENCES (CODE, DESCRIPTION)
	VALUES ('CR', 'VALOR DO CSLL INVÁLIDO')
INSERT INTO CNAB_OCCURRENCES (CODE, DESCRIPTION)
	VALUES ('CS', 'DATA DE VENCIMENTO DA FATURA INVÁLIDA')
INSERT INTO CNAB_OCCURRENCES (CODE, DESCRIPTION)
	VALUES ('DA', 'NÚMERO DE DEPEND. SALÁRIO FAMILIA INVALIDO')
INSERT INTO CNAB_OCCURRENCES (CODE, DESCRIPTION)
	VALUES ('DB', 'NÚMERO DE HORAS SEMANAIS INVÁLIDO')
INSERT INTO CNAB_OCCURRENCES (CODE, DESCRIPTION)
	VALUES ('DC', 'SALÁRIO DE CONTRIBUIÇÃO INSS INVÁLIDO')
INSERT INTO CNAB_OCCURRENCES (CODE, DESCRIPTION)
	VALUES ('DD', 'SALÁRIO DE CONTRIBUIÇÃO FGTS INVÁLIDO')
INSERT INTO CNAB_OCCURRENCES (CODE, DESCRIPTION)
	VALUES ('DE', 'VALOR TOTAL DOS PROVENTOS INVÁLIDO')
INSERT INTO CNAB_OCCURRENCES (CODE, DESCRIPTION)
	VALUES ('DF', 'VALOR TOTAL DOS DESCONTOS INVÁLIDO')
INSERT INTO CNAB_OCCURRENCES (CODE, DESCRIPTION)
	VALUES ('DG', 'VALOR LÍQUIDO NÃO NUMÉRICO')
INSERT INTO CNAB_OCCURRENCES (CODE, DESCRIPTION)
	VALUES ('DH', 'VALOR LIQ. INFORMADO DIFERE DO CALCULADO')
INSERT INTO CNAB_OCCURRENCES (CODE, DESCRIPTION)
	VALUES ('DI', 'VALOR DO SALÁRIO-BASE INVÁLIDO')
INSERT INTO CNAB_OCCURRENCES (CODE, DESCRIPTION)
	VALUES ('DJ', 'BASE DE CÁLCULO IRRF INVÁLIDA')
INSERT INTO CNAB_OCCURRENCES (CODE, DESCRIPTION)
	VALUES ('DK', 'BASE DE CÁLCULO FGTS INVÁLIDA')
INSERT INTO CNAB_OCCURRENCES (CODE, DESCRIPTION)
	VALUES ('DL', 'FORMA DE PAGAMENTO INCOMPATÍVEL COM HOLERITE')
INSERT INTO CNAB_OCCURRENCES (CODE, DESCRIPTION)
	VALUES ('DM', 'E-MAIL DO FAVORECIDO INVÁLIDO')
INSERT INTO CNAB_OCCURRENCES (CODE, DESCRIPTION)
	VALUES ('DV', 'DOC / TED DEVOLVIDO PELO BANCO FAVORECIDO')
INSERT INTO CNAB_OCCURRENCES (CODE, DESCRIPTION)
	VALUES ('D0', 'FINALIDADE DO HOLERITE INVÁLIDA')
INSERT INTO CNAB_OCCURRENCES (CODE, DESCRIPTION)
	VALUES ('D1', 'MÊS DE COMPETENCIA DO HOLERITE INVÁLIDA')
INSERT INTO CNAB_OCCURRENCES (CODE, DESCRIPTION)
	VALUES ('D2', 'DIA DA COMPETENCIA DO HOLETITE INVÁLIDA')
INSERT INTO CNAB_OCCURRENCES (CODE, DESCRIPTION)
	VALUES ('D3', 'CENTRO DE CUSTO INVÁLIDO')
INSERT INTO CNAB_OCCURRENCES (CODE, DESCRIPTION)
	VALUES ('D4', 'CAMPO NUMÉRICO DA FUNCIONAL INVÁLIDO')
INSERT INTO CNAB_OCCURRENCES (CODE, DESCRIPTION)
	VALUES ('D5', 'DATA INÍCIO DE FÉRIAS NÃO NUMÉRICA')
INSERT INTO CNAB_OCCURRENCES (CODE, DESCRIPTION)
	VALUES ('D6', 'DATA INÍCIO DE FÉRIAS INCONSISTENTE')
INSERT INTO CNAB_OCCURRENCES (CODE, DESCRIPTION)
	VALUES ('D7', 'DATA FIM DE FÉRIAS NÃO NUMÉRICO')
INSERT INTO CNAB_OCCURRENCES (CODE, DESCRIPTION)
	VALUES ('D8', 'DATA FIM DE FÉRIAS INCONSISTENTE')
INSERT INTO CNAB_OCCURRENCES (CODE, DESCRIPTION)
	VALUES ('D9', 'NÚMERO DE DEPENDENTES IR INVÁLIDO')
INSERT INTO CNAB_OCCURRENCES (CODE, DESCRIPTION)
	VALUES ('EM', 'CONFIRMAÇÃO DE OP EMITIDA')
INSERT INTO CNAB_OCCURRENCES (CODE, DESCRIPTION)
	VALUES ('EX', 'DEVOLUÇÃO DE OP NÃO SACADA PELO FAVORECIDO')
INSERT INTO CNAB_OCCURRENCES (CODE, DESCRIPTION)
	VALUES ('E0', 'TIPO DE MOVIMENTO HOLERITE INVÁLIDO')
INSERT INTO CNAB_OCCURRENCES (CODE, DESCRIPTION)
	VALUES ('E1', 'VALOR 01 DO HOLERITE / INFORME INVÁLIDO')
INSERT INTO CNAB_OCCURRENCES (CODE, DESCRIPTION)
	VALUES ('E2', 'VALOR 02 DO HOLERITE / INFORME INVÁLIDO')
INSERT INTO CNAB_OCCURRENCES (CODE, DESCRIPTION)
	VALUES ('E3', 'VALOR 03 DO HOLERITE / INFORME INVÁLIDO')
INSERT INTO CNAB_OCCURRENCES (CODE, DESCRIPTION)
	VALUES ('E4', 'VALOR 04 DO HOLERITE / INFORME INVÁLIDO')
INSERT INTO CNAB_OCCURRENCES (CODE, DESCRIPTION)
	VALUES ('FC', 'PAGAMENTO EFETUADO ATRAVÉS DE FINANCIAMENTO COMPROR')
INSERT INTO CNAB_OCCURRENCES (CODE, DESCRIPTION)
	VALUES ('FD', 'PAGAMENTO EFETUADO ATRAVÉS DE FINANCIAMENTO DESCOMPROR')
INSERT INTO CNAB_OCCURRENCES (CODE, DESCRIPTION)
	VALUES ('HA', 'ERRO NO HEADER DE ARQUIVO')
INSERT INTO CNAB_OCCURRENCES (CODE, DESCRIPTION)
	VALUES ('HM', 'ERRO NO HEADER DE LOTE')
INSERT INTO CNAB_OCCURRENCES (CODE, DESCRIPTION)
	VALUES ('IB', 'VALOR E/O U DATA DO DO CUMENTO INVÁLIDO')
INSERT INTO CNAB_OCCURRENCES (CODE, DESCRIPTION)
	VALUES ('IC', 'VALOR DO ABATIMENTO INVÁLIDO')
INSERT INTO CNAB_OCCURRENCES (CODE, DESCRIPTION)
	VALUES ('ID', 'VALOR DO DESCONTO INVÁLIDO')
INSERT INTO CNAB_OCCURRENCES (CODE, DESCRIPTION)
	VALUES ('IE', 'VALOR DA MORA INVÁLIDO')
INSERT INTO CNAB_OCCURRENCES (CODE, DESCRIPTION)
	VALUES ('IF', 'VALOR DA MULTA INVÁLIDO')
INSERT INTO CNAB_OCCURRENCES (CODE, DESCRIPTION)
	VALUES ('IG', 'VALOR DA DEDUÇÃO INVÁLIDO')
INSERT INTO CNAB_OCCURRENCES (CODE, DESCRIPTION)
	VALUES ('IH', 'VALOR DO ACRÉSCIMO INVÁLIDO')
INSERT INTO CNAB_OCCURRENCES (CODE, DESCRIPTION)
	VALUES ('II', 'DATA DE VENCIMENTO INVÁLIDA')
INSERT INTO CNAB_OCCURRENCES (CODE, DESCRIPTION)
	VALUES ('IJ', 'COMPETÊNCIA / PERÍODO REFERÊNCIA / PARCELA INVÁLIDA')
INSERT INTO CNAB_OCCURRENCES (CODE, DESCRIPTION)
	VALUES ('IK', 'TRIBUTO NÃO LIQUIDÁVEL VIA SISPAG OU NÃO CONVENIADO COM ITAÚ')
INSERT INTO CNAB_OCCURRENCES (CODE, DESCRIPTION)
	VALUES ('IL', 'CÓDIGO DE PAGAMENTO / EMPRESA /RECEITA INVÁLIDO')
INSERT INTO CNAB_OCCURRENCES (CODE, DESCRIPTION)
	VALUES ('IM', 'TIPO X FORMA NÃO COMPATÍVEL')
INSERT INTO CNAB_OCCURRENCES (CODE, DESCRIPTION)
	VALUES ('IN', 'BANCO/AGENCIA NÃO CADASTRADOS')
INSERT INTO CNAB_OCCURRENCES (CODE, DESCRIPTION)
	VALUES ('IO', 'DAC / VALOR / COMPETÊNCIA / IDENTIFICADOR DO LACRE INVÁLIDO')
INSERT INTO CNAB_OCCURRENCES (CODE, DESCRIPTION)
	VALUES ('IP', 'DAC DO CÓDIGO DE BARRAS INVÁLIDO')
INSERT INTO CNAB_OCCURRENCES (CODE, DESCRIPTION)
	VALUES ('IQ', 'DÍVIDA ATIVA OU NÚMERO DE ETIQUETA INVÁLIDO')
INSERT INTO CNAB_OCCURRENCES (CODE, DESCRIPTION)
	VALUES ('IR', 'PAGAMENTO ALTERADO')
INSERT INTO CNAB_OCCURRENCES (CODE, DESCRIPTION)
	VALUES ('IS', 'CONCESSIONÁRIA NÃO CONVENIADA COM ITAÚ')
INSERT INTO CNAB_OCCURRENCES (CODE, DESCRIPTION)
	VALUES ('IT', 'VALOR DO TRIBUTO INVÁLIDO')
INSERT INTO CNAB_OCCURRENCES (CODE, DESCRIPTION)
	VALUES ('IU', 'VALOR DA RECEITA BRUTA ACUMULADA INVÁLIDO')
INSERT INTO CNAB_OCCURRENCES (CODE, DESCRIPTION)
	VALUES ('IV', 'NÚMERO DO DOCUMENTO ORIGEM / REFERÊNCIA INVÁLIDO')
INSERT INTO CNAB_OCCURRENCES (CODE, DESCRIPTION)
	VALUES ('IX', 'CÓDIGO DO PRODUTO INVÁLIDO')
INSERT INTO CNAB_OCCURRENCES (CODE, DESCRIPTION)
	VALUES ('LA', 'DATA DE PAGAMENTO DE UM LOTE ALTERADA')
INSERT INTO CNAB_OCCURRENCES (CODE, DESCRIPTION)
	VALUES ('LC', 'LOTE DE PAGAMENTOS CANCELADO')
INSERT INTO CNAB_OCCURRENCES (CODE, DESCRIPTION)
	VALUES ('NA', 'PAGAMENTO CANCELADO POR FALTA DE AUTORIZAÇÃO')
INSERT INTO CNAB_OCCURRENCES (CODE, DESCRIPTION)
	VALUES ('NB', 'IDENTIFICAÇÃO DO TRIBUTO INVÁLIDA')
INSERT INTO CNAB_OCCURRENCES (CODE, DESCRIPTION)
	VALUES ('NC', 'EXERCÍCIO (ANO BASE) INVÁLIDO')
INSERT INTO CNAB_OCCURRENCES (CODE, DESCRIPTION)
	VALUES ('ND', 'CÓDIGO RENAVAM NÃO ENCONTRADO/INVÁLIDO')
INSERT INTO CNAB_OCCURRENCES (CODE, DESCRIPTION)
	VALUES ('NE', 'UF INVÁLIDA')
INSERT INTO CNAB_OCCURRENCES (CODE, DESCRIPTION)
	VALUES ('NF', 'CÓDIGO DO MUNICÍPIO INVÁLIDO')
INSERT INTO CNAB_OCCURRENCES (CODE, DESCRIPTION)
	VALUES ('NG', 'PLACA INVÁLIDA')
INSERT INTO CNAB_OCCURRENCES (CODE, DESCRIPTION)
	VALUES ('NH', 'OPÇÃO/PARCELA DE PAGAMENTO INVÁLIDA')
INSERT INTO CNAB_OCCURRENCES (CODE, DESCRIPTION)
	VALUES ('NI', 'TRIBUTO JÁ FOI PAGO OU ESTÁ VENCIDO')
INSERT INTO CNAB_OCCURRENCES (CODE, DESCRIPTION)
	VALUES ('NR', 'OPERAÇÃO NÃO REALIZADA')
INSERT INTO CNAB_OCCURRENCES (CODE, DESCRIPTION)
	VALUES ('PD', 'AQUISIÇÃO CONFIRMADA (EQUIVALE A OCORRÊNCIA 02 NO LAYOUT DE RISCO SACADO)')
INSERT INTO CNAB_OCCURRENCES (CODE, DESCRIPTION)
	VALUES ('RJ', 'REGISTRO REJEITADO')
INSERT INTO CNAB_OCCURRENCES (CODE, DESCRIPTION)
	VALUES ('RS', 'PAGAMENTO DISPONÍVEL PARA ANTECIPAÇÃO NO RISCO SACADO – MODALIDADE RISCO SACADO PÓS AUTORIZADO')
INSERT INTO CNAB_OCCURRENCES (CODE, DESCRIPTION)
	VALUES ('SS', 'PAGAMENTO CANCELADO POR INSUFICIÊNCIA DE SALDO/LIMITE DIÁRIO DE PAGTO')
INSERT INTO CNAB_OCCURRENCES (CODE, DESCRIPTION)
	VALUES ('TA', 'LOTE NÃO ACEITO - TOTAIS DO LOTE COM DIFERENÇA')
INSERT INTO CNAB_OCCURRENCES (CODE, DESCRIPTION)
	VALUES ('TI', 'TITULARIDADE INVÁLIDA')
INSERT INTO CNAB_OCCURRENCES (CODE, DESCRIPTION)
	VALUES ('X1', 'FORMA INCOMPATÍVEL COM LAYOUT 010')
INSERT INTO CNAB_OCCURRENCES (CODE, DESCRIPTION)
	VALUES ('X2', 'NÚMERO DA NOTA FISCAL INVÁLIDO')
INSERT INTO CNAB_OCCURRENCES (CODE, DESCRIPTION)
	VALUES ('X3', 'IDENTIFICADOR DE NF/CNPJ INVÁLIDO')
INSERT INTO CNAB_OCCURRENCES (CODE, DESCRIPTION)
	VALUES ('X4', 'FORMA 32 INVÁLIDA')
END;
GO

IF ( SELECT
		COUNT(*)
	FROM SITUATION
	WHERE NAME = 'AWAITING PROCESSING')
= 0
INSERT INTO SITUATION (NAME)
	VALUES ('AWAITING PROCESSING');
IF ( SELECT
		COUNT(*)
	FROM TRADUCTION_SITUATION
	WHERE SITUATION_TR = 'AGUARDANDO PROCESSAMENTO')
= 0
INSERT INTO TRADUCTION_SITUATION (COD_SITUATION, LANGUAGE, SITUATION_TR)
	VALUES ((SELECT COD_SITUATION FROM SITUATION WHERE NAME = 'AWAITING PROCESSING'), 'PORTUGUES', 'AGUARDANDO PROCESSAMENTO')
IF ( SELECT
		COUNT(*)
	FROM SITUATION
	WHERE NAME = 'PAYMENT PROCESSED')
= 0
INSERT INTO SITUATION (NAME)
	VALUES ('PAYMENT PROCESSED');
IF ( SELECT
		COUNT(*)
	FROM TRADUCTION_SITUATION
	WHERE SITUATION_TR = 'PAGAMENTO PROCESSADO')
= 0
INSERT INTO TRADUCTION_SITUATION (COD_SITUATION, LANGUAGE, SITUATION_TR)
	VALUES ((SELECT COD_SITUATION FROM SITUATION WHERE NAME = 'PAYMENT PROCESSED'), 'PORTUGUES', 'PAGAMENTO PROCESSADO')

	
IF ( SELECT
		COUNT(*)
	FROM SITUATION
	WHERE NAME = 'PROCESSING')
= 0
INSERT INTO SITUATION (NAME)
	VALUES ('PROCESSING');
IF ( SELECT
		COUNT(*)
	FROM TRADUCTION_SITUATION
	WHERE SITUATION_TR = 'PROCESSANDO')
= 0
INSERT INTO TRADUCTION_SITUATION (COD_SITUATION, LANGUAGE, SITUATION_TR)
	VALUES ((SELECT COD_SITUATION FROM SITUATION WHERE NAME = 'PROCESSING'), 'PORTUGUES', 'PROCESSANDO')

IF ( SELECT
		COUNT(*)
	FROM SITUATION
	WHERE NAME = 'AWAITING RETENTATIVE')
= 0
INSERT INTO SITUATION (NAME)
	VALUES ('AWAITING RETENTATIVE');
IF ( SELECT
		COUNT(*)
	FROM TRADUCTION_SITUATION
	WHERE SITUATION_TR = 'AGUARDANDO RETENTATIVA')
= 0
INSERT INTO TRADUCTION_SITUATION (COD_SITUATION, LANGUAGE, SITUATION_TR)
	VALUES ((SELECT COD_SITUATION FROM SITUATION WHERE NAME = 'AWAITING RETENTATIVE'), 'PORTUGUES', 'AGUARDANDO RETENTATIVA')

	IF ( SELECT
		COUNT(*)
	FROM SOURCE_PROCESS
	WHERE DESCRIPTION = 'PROCESS_CNAB_PAYMENT')
= 0
INSERT INTO SOURCE_PROCESS (CREATED_AT, DESCRIPTION, COD_USER_CREAT, CODE)
	VALUES (current_timestamp, 'PROCESS_CNAB_PAYMENT', 63, 'Processamento de Pagamentos via CNAB');

GO

CREATE PROCEDURE SP_REP_CNAB_PAYMENTS
(
	@COD_FILE INT
)
AS
BEGIN
SELECT
	ITEMS_LOT_CNAB_PAYMENT.COD_ITEM_LOT
   ,ITEMS_LOT_CNAB_PAYMENT.CREATED_AT
   ,ITEMS_LOT_CNAB_PAYMENT.COD_LOT_PAY
   ,ITEMS_LOT_CNAB_PAYMENT.COD_FIN_SCH_FILE
   ,ITEMS_LOT_CNAB_PAYMENT.COD_CNAB_OC
   ,ITEMS_LOT_CNAB_PAYMENT.FILE_SEQUENCE
   ,ITEMS_LOT_CNAB_PAYMENT.VALUE_PAYMENT
   ,ITEMS_LOT_CNAB_PAYMENT.SEQUENCE_FILENAME
   ,ITEMS_LOT_CNAB_PAYMENT.COD_EC
   ,ITEMS_LOT_CNAB_PAYMENT.CNPJ_EC
   ,ITEMS_LOT_CNAB_PAYMENT.EC_NAME
   ,ITEMS_LOT_CNAB_PAYMENT.AFFILIATOR
   ,ITEMS_LOT_CNAB_PAYMENT.CNPJ_AFF
   ,ITEMS_LOT_CNAB_PAYMENT.PAYMENT_DATE
   ,ITEMS_LOT_CNAB_PAYMENT.COD_SITUATION
   ,ITEMS_LOT_CNAB_PAYMENT.SITUATION_TR
   ,CNAB_OCCURRENCES.CODE
   ,CNAB_OCCURRENCES.[DESCRIPTION]
   ,VW_PROTOCOLS_FINANCE_SCHEDULE_FILE.PROTOCOL
FROM ITEMS_LOT_CNAB_PAYMENT
INNER JOIN CNAB_OCCURRENCES
	ON CNAB_OCCURRENCES.COD_CNAB_OC = ITEMS_LOT_CNAB_PAYMENT.COD_CNAB_OC
INNER JOIN VW_PROTOCOLS_FINANCE_SCHEDULE_FILE
	ON VW_PROTOCOLS_FINANCE_SCHEDULE_FILE.COD_FIN_SCH_FILE = ITEMS_LOT_CNAB_PAYMENT.COD_FIN_SCH_FILE
INNER JOIN LOT_CNAB_PAYMENT
	ON LOT_CNAB_PAYMENT.COD_LOT_PAY = ITEMS_LOT_CNAB_PAYMENT.COD_LOT_PAY
WHERE LOT_CNAB_PAYMENT.COD_CNAB_FILE_LOT = @COD_FILE
END