alter index PK_REPORT_CONSOLIDATED_TRANS_SUB    on dbo.REPORT_CONSOLIDATED_TRANS_SUB rebuild
alter index PK_REPORT_TRANSACTIONS_EXP    on dbo.REPORT_TRANSACTIONS_EXP rebuild
alter index IX_TRANSACTION_DATA_EXT_COD_TRAN    on dbo.TRANSACTION_DATA_EXT rebuild
alter index PK_PROCESS_BG_STATUS    on dbo.PROCESS_BG_STATUS rebuild
alter index PK__FINANCE___B1D32F3BFCEB389A    on dbo.FINANCE_CALENDAR rebuild
alter index IX_REPORT_EXP_AFFILIATOR_COMP_TRANDATE    on dbo.REPORT_TRANSACTIONS_EXP rebuild
alter index PK_TRANSACTION    on dbo."TRANSACTION" rebuild
alter index PK__REPORT_T__2C11B0EC53FB1C5D    on dbo.REPORT_TRANSACTIONS rebuild
alter index PK_TITLE    on dbo.TRANSACTION_TITLES rebuild
alter index IX_PROCESS_BD_STATUS_CODE_SOURCE    on dbo.PROCESS_BG_STATUS rebuild
alter index PK_REPORT_STATUS_TRANSACTION    on dbo.REPORT_STATUS_TRANSACTION rebuild
alter index IDX_TRAN_EXP_COD_TTYPE    on dbo."TRANSACTION" rebuild
alter index IX_ASS_TAX_CREATED_DEPTO    on dbo.ASS_TAX_DEPART rebuild
alter index PK_TRANSACTION_TITLES_COST    on dbo.TRANSACTION_TITLES_COST rebuild
alter index IX_ASS_TAX_DEPART_COD_INCL_COD_TTYPE_INTERVAL_BRAND    on dbo.ASS_TAX_DEPART rebuild
alter index IX_REP_CONS_REPORT_ACQUIRER    on dbo.REPORT_CONSOLIDATED_TRANS_SUB rebuild
alter index IX_FINANCE_CALENDAR_SIT_COD_BK_EC_ACTIVE    on dbo.FINANCE_CALENDAR rebuild
alter index IX_TRAN_TITLES_SITUATION_PREV_INC_TRAN_DATA    on dbo.TRANSACTION_TITLES rebuild
alter index IDX_TRAN_TITLES_CTE_RELEASES    on dbo.TRANSACTION_TITLES rebuild
alter index IX_TRAN_SITUATION_CREATED_AT_CONS    on dbo."TRANSACTION" rebuild
alter index IX_FIN_CALENDAR_ACTIVE_IC_PLOT_EC_AFF_FIN_SCHE    on dbo.FINANCE_CALENDAR rebuild
alter index IX_TITILES_COD_SIT_INC_PLOT_AMOUNT_PREV_PAY    on dbo.TRANSACTION_TITLES rebuild
alter index IX_TRAN_TITLES_SITUATION_COD_EC    on dbo.TRANSACTION_TITLES rebuild
alter index IX_TITLES_COD_EC_PROVISIONS_SEARCH    on dbo.TRANSACTION_TITLES rebuild
alter index IX_PROCESS_BG_STATUS_Status    on dbo.PROCESS_BG_STATUS rebuild
alter index IX_TRAN_TITLE_21052020    on dbo.TRANSACTION_TITLES rebuild
alter index IX_TRAN_TITLE_COD_EC_PREVISION_PAYDATE    on dbo.TRANSACTION_TITLES rebuild
alter index IX_FIN_CALENDAR_SIT_ACTIVE_IC_PREV    on dbo.FINANCE_CALENDAR rebuild
alter index IX_TRANSACTION_COD_SITUATION_CREATED_AT    on dbo."TRANSACTION" rebuild
alter index IX_FIN_cALENDAR_FIN_SCHED    on dbo.FINANCE_CALENDAR rebuild
alter index IX_FIN_RESUME_ACTIVE    on dbo.FINANCE_RESUME rebuild
alter index un_report_consolidated_trans_sub    on dbo.REPORT_CONSOLIDATED_TRANS_SUB rebuild
alter index PK__FINANCE___1862AF5D66909F32    on dbo.FINANCE_RESUME rebuild
alter index "IX_TITLES_[COD_FIN_CALENDAR_COD_SITUATION"    on dbo.TRANSACTION_TITLES rebuild
alter index nci_wi_REPORT_TRANSACTIONS_3C4B13980B5C3EE0DE0E4E618820CA82    on dbo.REPORT_TRANSACTIONS rebuild
alter index IX_FIN_CAL_ACTIVE_IC_PLT_COD_PAY_PROT    on dbo.FINANCE_CALENDAR rebuild
alter index IX_REP_DIARY_STONE    on dbo.REPORT_CONSOLIDATED_TRANS_SUB rebuild
alter index IX_REPORT_EC_SITUATION_TRAN_DATE    on dbo.REPORT_TRANSACTIONS rebuild
alter index IX_REPORT_EC_SITUATION_TRAN_DATE2    on dbo.REPORT_TRANSACTIONS rebuild
alter index IX_TR_SIT_BR_DATE    on dbo."TRANSACTION" rebuild
alter index IX_VALUE_SIT_TRANDATE_REP_EXP    on dbo.REPORT_TRANSACTIONS_EXP rebuild
alter index IX_REPORT_CONSOLIDATED_TRANS_SUB_COD_TRAN    on dbo.REPORT_CONSOLIDATED_TRANS_SUB rebuild
alter index IX_COD_SITUATION_COD_FIN_SCH_FILE    on dbo.TRANSACTION_TITLES rebuild
alter index IX_CREATED_AT_COD_SIT_TRAN_TITLE    on dbo.TRANSACTION_TITLES rebuild
alter index IX_TRAN_TITLE_FINANCE_PROT    on dbo.TRANSACTION_TITLES rebuild
alter index IX_FN_CALENDAR_ACTIVE_PROTOCOL    on dbo.FINANCE_CALENDAR rebuild
alter index IX_TRANSACTION_TITLES_COD_TRAN    on dbo.TRANSACTION_TITLES rebuild
alter index IX_TRANSACTION_TO_AMOUNT    on dbo."TRANSACTION" rebuild
alter index IX_FIN_TOPAY_ON_TITLES    on dbo.TRANSACTION_TITLES rebuild
alter index FINANCE_CALENDAR_ACTIVE_COD_EC_COD_SITUATION_COD_PAY_PROT    on dbo.FINANCE_CALENDAR rebuild

 

update statistics REPORT_CONSOLIDATED_TRANS_SUB
update statistics REPORT_TRANSACTIONS_EXP
update statistics TRANSACTION_DATA_EXT
update statistics PROCESS_BG_STATUS
update statistics FINANCE_CALENDAR
update statistics "TRANSACTION"
update statistics REPORT_TRANSACTIONS
update statistics TRANSACTION_TITLES
update statistics REPORT_STATUS_TRANSACTION
update statistics ASS_TAX_DEPART
update statistics TRANSACTION_TITLES_COST
update statistics FINANCE_RESUME