SELECT
	COMMERCIAL_ESTABLISHMENT.[NAME]
   ,COMMERCIAL_ESTABLISHMENT.[CPF_CNPJ]
   ,[PLAN].CODE
   ,TYPE_PLAN.DESCRIPTION
   ,BRAND.[GROUP]
   ,TRANSACTION_TYPE.CODE
   ,ASS_TAX_DEPART.QTY_INI_PLOTS
   ,ASS_TAX_DEPART.QTY_FINAL_PLOTS
   ,replace(replace(replace(convert(varchar(30), ASS_TAX_DEPART.PARCENTAGE, 1), ',', '|'), '.', ','), '|', '.') AS MDR
   ,replace(replace(replace(convert(varchar(30), ASS_TAX_DEPART.ANTICIPATION_PERCENTAGE, 1), ',', '|'), '.', ','), '|', '.') AS ANTECIPACAO
   ,replace(replace(replace(convert(varchar(30), ASS_TAX_DEPART.RATE, 1), ',', '|'), '.', ','), '|', '.') AS RATE
   ,ASS_TAX_DEPART.INTERVAL
   ,SOURCE_TRANSACTION.DESCRIPTION
FROM ASS_TAX_DEPART
JOIN DEPARTMENTS_BRANCH
	ON DEPARTMENTS_BRANCH.COD_DEPTO_BRANCH = ASS_TAX_DEPART.COD_DEPTO_BRANCH
JOIN BRANCH_EC
	ON BRANCH_EC.COD_BRANCH = DEPARTMENTS_BRANCH.COD_BRANCH
JOIN COMMERCIAL_ESTABLISHMENT
	ON COMMERCIAL_ESTABLISHMENT.COD_EC = BRANCH_EC.COD_EC
JOIN AFFILIATOR
	ON AFFILIATOR.COD_AFFILIATOR = COMMERCIAL_ESTABLISHMENT.COD_AFFILIATOR
LEFT JOIN EQUIPMENT_MODEL
	ON EQUIPMENT_MODEL.COD_MODEL = ASS_TAX_DEPART.COD_MODEL
JOIN [PLAN]
	ON [PLAN].COD_PLAN = ASS_TAX_DEPART.COD_PLAN
JOIN TYPE_PLAN
	ON TYPE_PLAN.COD_T_PLAN = [PLAN].COD_T_PLAN
JOIN TRANSACTION_TYPE
	ON TRANSACTION_TYPE.COD_TTYPE = ASS_TAX_DEPART.COD_TTYPE
JOIN BRAND
	ON BRAND.COD_BRAND = ASS_TAX_DEPART.COD_BRAND
JOIN SOURCE_TRANSACTION
	ON SOURCE_TRANSACTION.COD_SOURCE_TRAN = ASS_TAX_DEPART.COD_SOURCE_TRAN
WHERE AFFILIATOR.SUBDOMAIN = 'cnt'
AND ASS_TAX_DEPART.ACTIVE = 1