DECLARE @DEBIT_PS_QTY INT = ( SELECT
		COUNT(*)
	FROM PRODUCTS_ACQUIRER
	JOIN ACQUIRER
		ON ACQUIRER.COD_AC = PRODUCTS_ACQUIRER.COD_AC
	JOIN BRAND
		ON BRAND.COD_BRAND = PRODUCTS_ACQUIRER.COD_BRAND
	WHERE ACQUIRER.[GROUP] = 'PAGSEGURO'
	AND PRODUCTS_ACQUIRER.PLOT_VALUE = 1
	AND PRODUCTS_ACQUIRER.IS_SIMULATED = 0
	AND PRODUCTS_ACQUIRER.VISIBLE = 1
	AND BRAND.COD_TTYPE = 2)

DECLARE @CREDIT_PS_QTY INT = ( SELECT
		COUNT(*)
	FROM PRODUCTS_ACQUIRER
	JOIN ACQUIRER
		ON ACQUIRER.COD_AC = PRODUCTS_ACQUIRER.COD_AC
	JOIN BRAND
		ON BRAND.COD_BRAND = PRODUCTS_ACQUIRER.COD_BRAND
	WHERE ACQUIRER.[GROUP] = 'PAGSEGURO'
	AND PRODUCTS_ACQUIRER.PLOT_VALUE = 1
	AND PRODUCTS_ACQUIRER.IS_SIMULATED = 0
	AND PRODUCTS_ACQUIRER.VISIBLE = 1
	AND BRAND.COD_TTYPE = 1)

DECLARE @INSTALLMENTS_PS_QTY INT = ( SELECT
		COUNT(*)
	FROM PRODUCTS_ACQUIRER
	JOIN ACQUIRER
		ON ACQUIRER.COD_AC = PRODUCTS_ACQUIRER.COD_AC
	JOIN BRAND
		ON BRAND.COD_BRAND = PRODUCTS_ACQUIRER.COD_BRAND
	WHERE ACQUIRER.[GROUP] = 'PAGSEGURO'
	AND PRODUCTS_ACQUIRER.PLOT_VALUE = 2
	AND PRODUCTS_ACQUIRER.IS_SIMULATED = 0
	AND PRODUCTS_ACQUIRER.VISIBLE = 1
	AND BRAND.COD_TTYPE = 1)

--PARCELADO CLIENTE

	DECLARE @CLIENTDEBIT_PS_QTY INT = ( SELECT
		COUNT(*)
	FROM PRODUCTS_ACQUIRER
	JOIN ACQUIRER
		ON ACQUIRER.COD_AC = PRODUCTS_ACQUIRER.COD_AC
	JOIN BRAND
		ON BRAND.COD_BRAND = PRODUCTS_ACQUIRER.COD_BRAND
	WHERE ACQUIRER.[GROUP] = 'PAGSEGURO'
	AND PRODUCTS_ACQUIRER.PLOT_VALUE = 1
	AND PRODUCTS_ACQUIRER.IS_SIMULATED = 1
	AND PRODUCTS_ACQUIRER.VISIBLE = 1
	AND BRAND.COD_TTYPE = 2)

DECLARE @CLIENTCREDIT_PS_QTY INT = ( SELECT
		COUNT(*)
	FROM PRODUCTS_ACQUIRER
	JOIN ACQUIRER
		ON ACQUIRER.COD_AC = PRODUCTS_ACQUIRER.COD_AC
	JOIN BRAND
		ON BRAND.COD_BRAND = PRODUCTS_ACQUIRER.COD_BRAND
	WHERE ACQUIRER.[GROUP] = 'PAGSEGURO'
	AND PRODUCTS_ACQUIRER.PLOT_VALUE = 1
	AND PRODUCTS_ACQUIRER.IS_SIMULATED = 1
	AND PRODUCTS_ACQUIRER.VISIBLE = 1
	AND BRAND.COD_TTYPE = 1)

DECLARE @CLIENTINSTALLMENTS_PS_QTY INT = ( SELECT
		COUNT(*)
	FROM PRODUCTS_ACQUIRER
	JOIN ACQUIRER
		ON ACQUIRER.COD_AC = PRODUCTS_ACQUIRER.COD_AC
	JOIN BRAND
		ON BRAND.COD_BRAND = PRODUCTS_ACQUIRER.COD_BRAND
	WHERE ACQUIRER.[GROUP] = 'PAGSEGURO'
	AND PRODUCTS_ACQUIRER.PLOT_VALUE = 2
	AND PRODUCTS_ACQUIRER.IS_SIMULATED = 1
	AND PRODUCTS_ACQUIRER.VISIBLE = 1
	AND BRAND.COD_TTYPE = 1)

SELECT
	* INTO #TMP_PRD_UNA_EC
FROM PRODUCTS_UNAVAILABLE_EC
WHERE COD_EC IS NOT NULL
--AND PRODUCTS_CUSTOMIZED = 1

WHILE ( SELECT
		COUNT(*)
	FROM #TMP_PRD_UNA_EC)
> 0
BEGIN

DECLARE @CURRENT_EC INT = (SELECT TOP 1
		COD_EC
	FROM #TMP_PRD_UNA_EC)

INSERT INTO PRODUCT_ACQUIRE_FILTER (COD_EC
, ONLINE
, PRESENTIAL
, DEBIT
, CREDIT
, CREDIT_INSTALLMENTS
, CLIENT_INSTALLMENT
, CLIENT_DEBIT
, CLIENT_CREDIT
, RATE_FREE
, CREATED_AT
, COD_USER)
	VALUES (@CURRENT_EC, 0, 0, 0, 0, 0, 0, 0, 0, 0, CURRENT_TIMESTAMP, 173)

DECLARE @CURRENT_LINE INT = @@identity


IF (SELECT
			IS_SIMULATED
		FROM #TMP_PRD_UNA_EC
		WHERE COD_EC = @CURRENT_EC)
	= 0
BEGIN

UPDATE PRODUCT_ACQUIRE_FILTER
SET CLIENT_INSTALLMENT = 1
   ,CLIENT_DEBIT = 1
   ,CLIENT_CREDIT = 1
WHERE COD_EC = @CURRENT_EC

END

IF (SELECT
			NOT_SIMULATED
		FROM #TMP_PRD_UNA_EC
		WHERE COD_EC = @CURRENT_EC)
	= 0
BEGIN

UPDATE PRODUCT_ACQUIRE_FILTER
SET DEBIT = 1
   ,CREDIT = 1
   ,CREDIT_INSTALLMENTS = 1
WHERE COD_EC = @CURRENT_EC

END


IF (SELECT
			PRODUCTS_CUSTOMIZED
		FROM #TMP_PRD_UNA_EC
		WHERE COD_EC = @CURRENT_EC)
	= 1
BEGIN

DECLARE @DEBIT_ACTUAL INT;
DECLARE @CREDIT_ACTUAL INT;
DECLARE @INSTALLMENT_ACTUAL INT;
DECLARE @CL_DEBIT_ACTUAL INT;
DECLARE @CL_CREDIT_ACTUAL INT;
DECLARE @CL_INSTALLMENT_ACTUAL INT;

SELECT
	@DEBIT_ACTUAL = (SELECT
			COUNT(*)
		FROM PRODUCTS_UNAVAILABLE_EC
		JOIN CUSTOMIZED_UNAVAILABLE_PRODUCTS
			ON CUSTOMIZED_UNAVAILABLE_PRODUCTS.COD_PR_UN_EC = PRODUCTS_UNAVAILABLE_EC.COD_PR_UN_EC
		JOIN PRODUCTS_ACQUIRER
			ON PRODUCTS_ACQUIRER.COD_PR_ACQ = CUSTOMIZED_UNAVAILABLE_PRODUCTS.COD_PR_ACQ
		JOIN ACQUIRER
			ON ACQUIRER.COD_AC = PRODUCTS_ACQUIRER.COD_AC
		JOIN BRAND
			ON BRAND.COD_BRAND = PRODUCTS_ACQUIRER.COD_BRAND
		WHERE ACQUIRER.[GROUP] = 'PAGSEGURO'
		AND PRODUCTS_ACQUIRER.PLOT_VALUE = 1
		AND PRODUCTS_ACQUIRER.IS_SIMULATED = 0
		AND PRODUCTS_ACQUIRER.VISIBLE = 1
		AND BRAND.COD_TTYPE = 2
		AND COD_EC = @CURRENT_EC)
   ,@CREDIT_ACTUAL = (SELECT
			COUNT(*)
		FROM PRODUCTS_UNAVAILABLE_EC
		JOIN CUSTOMIZED_UNAVAILABLE_PRODUCTS
			ON CUSTOMIZED_UNAVAILABLE_PRODUCTS.COD_PR_UN_EC = PRODUCTS_UNAVAILABLE_EC.COD_PR_UN_EC
		JOIN PRODUCTS_ACQUIRER
			ON PRODUCTS_ACQUIRER.COD_PR_ACQ = CUSTOMIZED_UNAVAILABLE_PRODUCTS.COD_PR_ACQ
		JOIN ACQUIRER
			ON ACQUIRER.COD_AC = PRODUCTS_ACQUIRER.COD_AC
		JOIN BRAND
			ON BRAND.COD_BRAND = PRODUCTS_ACQUIRER.COD_BRAND
		WHERE ACQUIRER.[GROUP] = 'PAGSEGURO'
		AND PRODUCTS_ACQUIRER.PLOT_VALUE = 1
		AND PRODUCTS_ACQUIRER.IS_SIMULATED = 0
		AND PRODUCTS_ACQUIRER.VISIBLE = 1
		AND BRAND.COD_TTYPE = 1
		AND COD_EC = @CURRENT_EC)
   ,@INSTALLMENT_ACTUAL = (SELECT
			COUNT(*)
		FROM PRODUCTS_UNAVAILABLE_EC
		JOIN CUSTOMIZED_UNAVAILABLE_PRODUCTS
			ON CUSTOMIZED_UNAVAILABLE_PRODUCTS.COD_PR_UN_EC = PRODUCTS_UNAVAILABLE_EC.COD_PR_UN_EC
		JOIN PRODUCTS_ACQUIRER
			ON PRODUCTS_ACQUIRER.COD_PR_ACQ = CUSTOMIZED_UNAVAILABLE_PRODUCTS.COD_PR_ACQ
		JOIN ACQUIRER
			ON ACQUIRER.COD_AC = PRODUCTS_ACQUIRER.COD_AC
		JOIN BRAND
			ON BRAND.COD_BRAND = PRODUCTS_ACQUIRER.COD_BRAND
		WHERE ACQUIRER.[GROUP] = 'PAGSEGURO'
		AND PRODUCTS_ACQUIRER.PLOT_VALUE = 2
		AND PRODUCTS_ACQUIRER.IS_SIMULATED = 0
		AND PRODUCTS_ACQUIRER.VISIBLE = 1
		AND BRAND.COD_TTYPE = 1
		AND COD_EC = @CURRENT_EC)
   ,@CL_DEBIT_ACTUAL = (SELECT
			COUNT(*)
		FROM PRODUCTS_UNAVAILABLE_EC
		JOIN CUSTOMIZED_UNAVAILABLE_PRODUCTS
			ON CUSTOMIZED_UNAVAILABLE_PRODUCTS.COD_PR_UN_EC = PRODUCTS_UNAVAILABLE_EC.COD_PR_UN_EC
		JOIN PRODUCTS_ACQUIRER
			ON PRODUCTS_ACQUIRER.COD_PR_ACQ = CUSTOMIZED_UNAVAILABLE_PRODUCTS.COD_PR_ACQ
		JOIN ACQUIRER
			ON ACQUIRER.COD_AC = PRODUCTS_ACQUIRER.COD_AC
		JOIN BRAND
			ON BRAND.COD_BRAND = PRODUCTS_ACQUIRER.COD_BRAND
		WHERE ACQUIRER.[GROUP] = 'PAGSEGURO'
		AND PRODUCTS_ACQUIRER.PLOT_VALUE = 1
		AND PRODUCTS_ACQUIRER.IS_SIMULATED = 1
		AND PRODUCTS_ACQUIRER.VISIBLE = 1
		AND BRAND.COD_TTYPE = 2
		AND COD_EC = @CURRENT_EC)
   ,@CL_CREDIT_ACTUAL = (SELECT
			COUNT(*)
		FROM PRODUCTS_UNAVAILABLE_EC
		JOIN CUSTOMIZED_UNAVAILABLE_PRODUCTS
			ON CUSTOMIZED_UNAVAILABLE_PRODUCTS.COD_PR_UN_EC = PRODUCTS_UNAVAILABLE_EC.COD_PR_UN_EC
		JOIN PRODUCTS_ACQUIRER
			ON PRODUCTS_ACQUIRER.COD_PR_ACQ = CUSTOMIZED_UNAVAILABLE_PRODUCTS.COD_PR_ACQ
		JOIN ACQUIRER
			ON ACQUIRER.COD_AC = PRODUCTS_ACQUIRER.COD_AC
		JOIN BRAND
			ON BRAND.COD_BRAND = PRODUCTS_ACQUIRER.COD_BRAND
		WHERE ACQUIRER.[GROUP] = 'PAGSEGURO'
		AND PRODUCTS_ACQUIRER.PLOT_VALUE = 1
		AND PRODUCTS_ACQUIRER.IS_SIMULATED = 0
		AND PRODUCTS_ACQUIRER.VISIBLE = 1
		AND BRAND.COD_TTYPE = 1
		AND COD_EC = @CURRENT_EC)
   ,@CL_INSTALLMENT_ACTUAL = (SELECT
			COUNT(*)
		FROM PRODUCTS_UNAVAILABLE_EC
		JOIN CUSTOMIZED_UNAVAILABLE_PRODUCTS
			ON CUSTOMIZED_UNAVAILABLE_PRODUCTS.COD_PR_UN_EC = PRODUCTS_UNAVAILABLE_EC.COD_PR_UN_EC
		JOIN PRODUCTS_ACQUIRER
			ON PRODUCTS_ACQUIRER.COD_PR_ACQ = CUSTOMIZED_UNAVAILABLE_PRODUCTS.COD_PR_ACQ
		JOIN ACQUIRER
			ON ACQUIRER.COD_AC = PRODUCTS_ACQUIRER.COD_AC
		JOIN BRAND
			ON BRAND.COD_BRAND = PRODUCTS_ACQUIRER.COD_BRAND
		WHERE ACQUIRER.[GROUP] = 'PAGSEGURO'
		AND PRODUCTS_ACQUIRER.PLOT_VALUE = 2
		AND PRODUCTS_ACQUIRER.IS_SIMULATED = 1
		AND PRODUCTS_ACQUIRER.VISIBLE = 1
		AND BRAND.COD_TTYPE = 1
		AND COD_EC = @CURRENT_EC)
FROM PRODUCTS_UNAVAILABLE_EC
JOIN CUSTOMIZED_UNAVAILABLE_PRODUCTS
	ON CUSTOMIZED_UNAVAILABLE_PRODUCTS.COD_PR_UN_EC = PRODUCTS_UNAVAILABLE_EC.COD_PR_UN_EC
WHERE COD_EC = @CURRENT_EC

UPDATE PRODUCT_ACQUIRE_FILTER
SET DEBIT =
	CASE
		WHEN (SELECT TOP 1
					NOT_SIMULATED
				FROM PRODUCTS_UNAVAILABLE_EC
				WHERE COD_EC = @CURRENT_EC)
			= 1 THEN IIF(@DEBIT_ACTUAL = @DEBIT_PS_QTY, 1, 0)
		ELSE 1
	END
   ,CREDIT =
	CASE
		WHEN (SELECT TOP 1
					NOT_SIMULATED
				FROM PRODUCTS_UNAVAILABLE_EC
				WHERE COD_EC = @CURRENT_EC)
			= 1 THEN IIF(@CREDIT_ACTUAL = @CREDIT_PS_QTY, 1, 0)
		ELSE 1
	END
   ,CREDIT_INSTALLMENTS =
	CASE
		WHEN (SELECT TOP 1
					NOT_SIMULATED
				FROM PRODUCTS_UNAVAILABLE_EC
				WHERE COD_EC = @CURRENT_EC)
			= 1 THEN IIF(@INSTALLMENT_ACTUAL = @INSTALLMENTS_PS_QTY, 1, 0)
		ELSE 1
	END
   ,CLIENT_DEBIT =
	CASE
		WHEN (SELECT TOP 1
					IS_SIMULATED
				FROM PRODUCTS_UNAVAILABLE_EC
				WHERE COD_EC = @CURRENT_EC)
			= 1 THEN IIF(@CL_DEBIT_ACTUAL = @CLIENTDEBIT_PS_QTY, 1, 0)
		ELSE 1
	END
   ,CLIENT_CREDIT =
	CASE
		WHEN (SELECT TOP 1
					IS_SIMULATED
				FROM PRODUCTS_UNAVAILABLE_EC
				WHERE COD_EC = @CURRENT_EC)
			= 1 THEN IIF(@CL_CREDIT_ACTUAL = @CLIENTCREDIT_PS_QTY, 1, 0)
		ELSE 1
	END
   ,CLIENT_INSTALLMENT =
	CASE
		WHEN (SELECT TOP 1
					IS_SIMULATED
				FROM PRODUCTS_UNAVAILABLE_EC
				WHERE COD_EC = @CURRENT_EC)
			= 1 THEN IIF(@CL_INSTALLMENT_ACTUAL = @CLIENTINSTALLMENTS_PS_QTY, 1, 0)
		ELSE 1
	END
WHERE COD_EC = @CURRENT_EC

END

DELETE FROM #TMP_PRD_UNA_EC
WHERE COD_EC = @CURRENT_EC

END;

DROP TABLE #TMP_PRD_UNA_EC
--DELETE FROM PRODUCT_ACQUIRE_FILTER

GO

INSERT INTO PRODUCT_ACQUIRE_FILTER (COD_AFFILIATOR, COD_EC, COD_MODEL, ONLINE, PRESENTIAL, DEBIT, CREDIT, CREDIT_INSTALLMENTS, CLIENT_INSTALLMENT, CLIENT_DEBIT, CLIENT_CREDIT, RATE_FREE, CREATED_AT, COD_USER)
	SELECT DISTINCT
		PRODUCTS_UNAVAILABLE_EC.COD_AFFILIATOR
	   ,NULL
	   ,NULL
	   ,0
	   ,0
	   ,0
	   ,0
	   ,0
	   ,0
	   ,1
	   ,1
	   ,0
	   ,CURRENT_TIMESTAMP
	   ,173
	FROM PRODUCTS_UNAVAILABLE_EC
	JOIN CUSTOMIZED_UNAVAILABLE_PRODUCTS
		ON CUSTOMIZED_UNAVAILABLE_PRODUCTS.COD_PR_UN_EC = PRODUCTS_UNAVAILABLE_EC.COD_PR_UN_EC
	WHERE COD_AFFILIATOR IS NOT NULL