update ACQUIRER_KEYS_CREDENTIALS
set VALUE = '43648a7e-83f0-4413-a21c-2ac67d79db40'
where COD_AC = 8
  and CODE_EC is null
  and NAME = 'M_ID'
update ACQUIRER_KEYS_CREDENTIALS
set VALUE = '005558094'
where COD_AC = 8
  and CODE_EC is null
  and NAME = 'MID'
update ACQUIRER_KEYS_CREDENTIALS
set VALUE = 'FYESHFVMNXWECRZKRRFBXVFDIHRBBTKWKWINAEMV'
where COD_AC = 8
  and CODE_EC is null
  and NAME = 'M_KEY'
update ACQUIRER_KEYS_CREDENTIALS
set CODE_EC = null
where CODE_EC = 689465
update ACQUIRER_KEYS_CREDENTIALS
set COD_AFFILIATOR = null
where COD_AFFILIATOR = 35
update ACQUIRER_KEYS_CREDENTIALS
set VALUE = 0
where NAME = 'PRIORITY'
  and COD_AC = 8
update ACQUIRER_KEYS_CREDENTIALS
set VALUE = 1
where NAME = 'PRIORITY'
  and COD_AC = 18
update ACQUIRER_KEYS_CREDENTIALS
set VALUE = 2
where NAME = 'PRIORITY'
  and COD_AC = 25