UPDATE ASS_DEPTO_EQUIP SET
	COD_DEPTO_BRANCH = 11527
FROM ASS_DEPTO_EQUIP
JOIN EQUIPMENT ON EQUIPMENT.COD_EQUIP = ASS_DEPTO_EQUIP.COD_EQUIP
WHERE EQUIPMENT.SERIAL = '7M414771'


select * from VW_COMPANY_EC_AFF_BR_DEP_EQUIP where cod_ec = 11543

SELECT * FROM EQUIPMENT WHERE SERIAL = '7M414771'


INSERT INTO EQUIPMENT (CREATED_AT,TID, SERIAL, COD_MODEL, COD_COMP, ACTIVE, CHIP)
				SELECT CREATED_AT,'15616516', '7M414771', COD_MODEL, COD_COMP, ACTIVE, CHIP FROM EQUIPMENT WHERE COD_EQUIP = 3


SELECT * FROM ROUTE_ACQUIRER WHERE COD_EQUIP =28868

INSERT INTO ROUTE_ACQUIRER (CREATED_AT, COD_EQUIP, COD_USER, ACTIVE, CONF_TYPE, COD_BRAND, COD_AC, COD_SOURCE_TRAN)
					SELECT CREATED_AT, 35642, COD_USER, ACTIVE, CONF_TYPE, COD_BRAND, COD_AC, COD_SOURCE_TRAN FROM ROUTE_ACQUIRER WHERE COD_EQUIP = 28868


					EXEC SP_LOAD_TABLES_EQUIP 28868
					EXEC SP_LOAD_TABLES_EQUIP 35642