SELECT
	CONCAT(dbo.LPAD(ISNULL(OPERATION.CODE, 0), 3, '0'), dbo.LPAD(ACCOUNT, 8, '0')),
	ACCOUNT
FROM BANK_DETAILS_EC
LEFT JOIN OPERATION_BANK
	ON OPERATION_BANK.COD_OPER_BANK = BANK_DETAILS_EC.COD_OPER_BANK
LEFT JOIN OPERATION
	ON OPERATION.COD_OPER = OPERATION_BANK.COD_OPER
WHERE LEN(ACCOUNT) > 8
AND BANK_DETAILS_EC.ACTIVE = 1

--UPDATE BANK_DETAILS_EC
--SET ACCOUNT = CONCAT(dbo.LPAD(ISNULL(OPERATION.CODE, 0), 3, '0'), dbo.LPAD(ACCOUNT, 8, '0'))
--FROM BANK_DETAILS_EC
--LEFT JOIN OPERATION_BANK
--	ON OPERATION_BANK.COD_OPER_BANK = BANK_DETAILS_EC.COD_OPER_BANK
--LEFT JOIN OPERATION
--	ON OPERATION.COD_OPER = OPERATION_BANK.COD_OPER
--WHERE LEN(ACCOUNT) < 8
--AND BANK_DETAILS_EC.ACTIVE = 1



