CREATE VIEW VW_ECS_INFO_COMMERCIAL_DEPARTMENT
AS
SELECT
	ce.NAME AS 'NOME FANTASIA'
   ,ce.TRADING_NAME AS 'RAZÃO SOCIAL'
   ,a.NAME AS 'AFILIADOR'
   ,ce.CPF_CNPJ AS 'CNPJ EC'
   ,ce.EMAIL AS 'E-MAIL EC'
   ,USERS.COD_ACCESS AS 'USUARIO EC'
   ,pa.NAME AS 'PERFIL USUARIO'
   ,tc.NAME AS 'TIPO CONTATO'
   ,co.NAME AS 'OPERADORA'
   ,cb.DDI
   ,cb.DDD
   ,cb.NUMBER AS 'TELEFONE'
   ,USERS.COD_ACCESS AS 'USUARIO'
   ,ab.ADDRESS AS 'RUA'
   ,ab.NUMBER AS 'NUMERO'
   ,ab.COMPLEMENT AS 'COMPLEMENTO'
   ,n.NAME AS 'BAIRRO'
   ,ab.CEP
   ,c.NAME AS 'CIDADE'
   ,s.NAME AS 'ESTADO'
   ,s.UF    
   ,BANKS.CODE AS 'CÓD BANCO'
   ,BANKS.NAME AS 'NOME BANCO'
   ,bde.AGENCY AS 'AGÊNCIA'
   ,bde.DIGIT_AGENCY AS 'DIGITO AGÊNCIA'
   ,bde.ACCOUNT AS 'CONTA' 
   ,bde.DIGIT_ACCOUNT AS 'DIGITO CONTA'
FROM COMMERCIAL_ESTABLISHMENT ce
INNER JOIN BRANCH_EC be
	ON ce.COD_EC = be.COD_EC
INNER JOIN ADDRESS_BRANCH ab
	ON be.COD_BRANCH = ab.COD_BRANCH
INNER JOIN CONTACT_BRANCH cb
	ON be.COD_BRANCH = cb.COD_BRANCH
INNER JOIN USERS
	ON USERS.COD_EC = ce.COD_EC
INNER JOIN BANK_DETAILS_EC bde
	ON be.COD_BRANCH = bde.COD_BRANCH
INNER JOIN NEIGHBORHOOD n
	ON ab.COD_NEIGH = n.COD_NEIGH
INNER JOIN CITY c
	ON n.COD_CITY = c.COD_CITY
INNER JOIN STATE s
	ON c.COD_STATE = s.COD_STATE
INNER JOIN TYPE_CONTACT tc
	ON cb.COD_TP_CONT = tc.COD_TP_CONT
INNER JOIN CELL_OPERATOR co
	ON cb.COD_OPER = co.COD_OPER
INNER JOIN AFFILIATOR a
	ON a.COD_AFFILIATOR = ce.COD_AFFILIATOR
INNER JOIN PROFILE_ACCESS pa
	ON USERS.COD_PROFILE = pa.COD_PROFILE
INNER JOIN BANKS
	ON bde.COD_BANK = BANKS.COD_BANK
WHERE ab.ACTIVE = 1
AND bde.ACTIVE = 1
--ORDER BY a.NAME,
--ce.NAME