DECLARE @QTD INT;
DECLARE @CODE INT;
DECLARE @STATUS_PROCESSED INT;

DECLARE @DUPLICATED_TIDS AS CURSOR;

SET @DUPLICATED_TIDS = CURSOR FOR SELECT
	COUNT(*)
   ,CODE
   ,STATUS_PROCESSED
FROM PROCESS_BG_STATUS
WHERE COD_SOURCE_PROCESS = 3
AND STATUS_PROCESSED = 0
GROUP BY CODE
		,STATUS_PROCESSED
HAVING COUNT(*) > 1;

OPEN @DUPLICATED_TIDS;

FETCH NEXT FROM @DUPLICATED_TIDS INTO @QTD, @CODE, @STATUS_PROCESSED;

WHILE @@fetch_status = 0
BEGIN
	UPDATE TOP(@QTD - 1) PROCESS_BG_STATUS SET STATUS_PROCESSED = 1 WHERE CODE = @CODE AND STATUS_PROCESSED = @STATUS_PROCESSED;
	FETCH NEXT FROM @DUPLICATED_TIDS INTO @QTD, @CODE, @STATUS_PROCESSED;
END;

