	DECLARE @DUPLICATED_TIDS AS CURSOR;
	DECLARE @COD_CITY INT;
	DECLARE @CITY_CODE INT;


SET @DUPLICATED_TIDS = CURSOR FOR SELECT
	COD_CITY
   ,CITY_CODE
FROM CITY
	
OPEN @DUPLICATED_TIDS;

	FETCH NEXT FROM @DUPLICATED_TIDS INTO @COD_CITY, @CITY_CODE;

	WHILE @@fetch_status = 0
	BEGIN
		PRINT N'UPDATE CITY SET CITY_CODE = ' + CAST(@CITY_CODE AS VARCHAR(400)) + ' WHERE COD_CITY = ' + CAST(@COD_CITY AS VARCHAR(400))
		FETCH NEXT FROM @DUPLICATED_TIDS INTO @COD_CITY, @CITY_CODE;
	END