	DECLARE @CODE VARCHAR(200);
	DECLARE @QTD INT;
	DECLARE @DUPLICATED_TIDS AS CURSOR;
	DECLARE @SERIAL_NEW_TID AS CURSOR;
	DECLARE @COD_TID INT;
	DECLARE @NEW_TID VARCHAR(300);

	DECLARE @COD_DAT_EQUIP_AC INT;

	SET @DUPLICATED_TIDS = CURSOR FOR SELECT
		COUNT(CODE)
	   ,CODE
	FROM DATA_EQUIPMENT_AC
	GROUP BY CODE
			,ACTIVE
	HAVING COUNT(CODE) > 1;

	OPEN @DUPLICATED_TIDS;

	FETCH NEXT FROM @DUPLICATED_TIDS INTO @QTD, @CODE;

	WHILE @@fetch_status = 0
	BEGIN
	SET @SERIAL_NEW_TID = CURSOR FOR SELECT
		COD_DAT_EQUIP_AC
	FROM DATA_EQUIPMENT_AC
	WHERE CODE = @CODE;

		OPEN @SERIAL_NEW_TID;

		FETCH NEXT FROM @SERIAL_NEW_TID INTO @COD_DAT_EQUIP_AC;
		
		WHILE @@fetch_status = 0
		BEGIN

	SELECT TOP 1
		@NEW_TID = TID
	   ,@COD_TID = COD_DATA_EQUIP
	FROM DATA_TID_AVAILABLE_EC
	WHERE COD_AC = 12
	AND AVAILABLE = 1
	AND ACTIVE = 1
	AND TYPE_KEY_AC = 'PRESENCIAL'
	AND NAME = 'TID';

	UPDATE DATA_EQUIPMENT_AC
	SET CODE = @NEW_TID
	WHERE COD_DAT_EQUIP_AC = @COD_DAT_EQUIP_AC;

	UPDATE DATA_TID_AVAILABLE_EC
	SET ACTIVE = 0
	   ,AVAILABLE = 0
	WHERE COD_DATA_EQUIP = @COD_TID;

	FETCH NEXT FROM @SERIAL_NEW_TID INTO @COD_DAT_EQUIP_AC;
	END

	END;


	SELECT * FROM DATA_EQUIPMENT_AC ORDER BY 1 DESC