UPDATE [TRANSACTION] SET COD_COMP = NULL;
GO
UPDATE [TRANSACTION_TITLES] SET COD_TRAN = NULL;
GO
UPDATE COMMERCIAL_ESTABLISHMENT SET COD_COMP = NULL, COD_SEG = NULL, COD_RISK_SITUATION = NULL;
UPDATE BRANCH_EC SET COD_EC = NULL;
UPDATE [PLAN] SET COD_COMP = NULL;
UPDATE ASS_TAX_DEPART SET COD_DEPTO_BRANCH = NULL;
UPDATE USERS SET COD_COMP = NULL, COD_ACCESS = NEWID(), EMAIL = 'RTSAGDHA@UDAUBASD.C', COD_EC = NULL WHERE COD_ACCESS NOT IN ('kennedy.alef', 'gian.cort');
UPDATE RELEASE_ADJUSTMENTS SET COD_EC = NULL;
UPDATE ASS_DEPTO_EQUIP SET COD_EQUIP = NULL, ACTIVE = 0, COD_DEPTO_BRANCH = NULL;
UPDATE SALES_REPRESENTATIVE SET COD_USER = NULL;
UPDATE AFFILIATOR SET COD_COMP = NULL, CPF_CNPJ = '34125678123';
TRUNCATE TABLE REPORT_TRANSACTIONS;
TRUNCATE TABLE REPORT_TRANSACTIONS_EXP;
TRUNCATE TABLE REPORT_CONSOLIDATED_TRANS_SUB;
UPDATE PROTOCOLS SET COD_EC = NULL;
TRUNCATE TABLE REPORT_STATUS_TRANSACTION;