
IF NOT EXISTS (SELECT
		1
	FROM SYS.COLUMNS
	WHERE NAME = N'PAGSEGURO_CODE'
	AND object_id = OBJECT_ID(N'REPORT_TRANSACTIONS_EXP'))
BEGIN
ALTER TABLE REPORT_TRANSACTIONS_EXP
ADD PAGSEGURO_CODE VARCHAR(255)
END
GO

IF NOT EXISTS (SELECT
		1
	FROM SYS.COLUMNS
	WHERE NAME = N'PAGSEGURO_CODE'
	AND object_id = OBJECT_ID(N'RECONCILE_TRAN_INVALID'))
BEGIN
ALTER TABLE RECONCILE_TRAN_INVALID
ADD PAGSEGURO_CODE VARCHAR(255)
END
GO
IF OBJECT_ID('SP_REG_RECONCILE_ACQUIRER_TRANSACTION') IS NOT NULL DROP PROCEDURE SP_REG_RECONCILE_ACQUIRER_TRANSACTION
GO
IF OBJECT_ID('SP_REG_RECONCILE_INVALID') IS NOT NULL DROP PROCEDURE SP_REG_RECONCILE_INVALID
GO
IF TYPE_ID('TP_RECONCILE') IS NOT NULL DROP TYPE TP_RECONCILE
GO
IF TYPE_ID('[TP_INVALID_TRANSACTION]') IS NOT NULL DROP TYPE [TP_INVALID_TRANSACTION]
GO
CREATE TYPE [dbo].[TP_RECONCILE] AS TABLE(
	[COD_TRAN] [int] NULL,
	[COD_SITUATION] [int] NULL,
	[DESCRIPTION] [varchar](250) NULL,
	[TRANSACTION_ID] [varchar](250) NULL,
	PAGSEGURO_CODE VARCHAR(255) NULL
)
GO

CREATE TYPE [dbo].[TP_INVALID_TRANSACTION] AS TABLE(
	[FILE_NAME] [varchar](255) NULL,
	[COD_AC] [int] NULL,
	[NSU_EXT] [varchar](255) NULL,
	[AUTH_CODE] [varchar](255) NULL,
	[BRAND] [varchar](255) NULL,
	[AMOUNT] [decimal](22, 6) NULL,
	[NET_AMOUNT] [decimal](22, 6) NULL,
	[TRAN_DATE] [datetime] NULL,
	[PAN] [varchar](255) NULL,
	[RECONCILE_DATE] [date] NULL,
	[COD_TITLE] [int] NULL,
	[COD_REC_TYPE] [int] NULL,
	[PREVISION_PAYMENT] [datetime] NULL,
	PAGSEGURO_CODE VARCHAR(255) NULL
)
GO
CREATE PROCEDURE SP_REG_RECONCILE_ACQUIRER_TRANSACTION
(  
    @TP TP_RECONCILE READONLY  
)  
AS  
BEGIN
 
  
    DECLARE @GETDATE DATETIME = DBO.FN_FUS_UTF(GETDATE());

	UPDATE REPORT_TRANSACTIONS_EXP
	SET RECONCILED = 1
	   ,COD_REC_SIT = TP.COD_SITUATION
	   ,RECONCILE_DATE = @GETDATE
	   ,RECONCILE_DESCRIPTION = TP.DESCRIPTION
	   ,RECONCILE_ID = TP.TRANSACTION_ID
	   ,PAGSEGURO_CODE = TP.PAGSEGURO_CODE
	FROM REPORT_TRANSACTIONS_EXP
	JOIN @TP TP
		ON TP.COD_TRAN = REPORT_TRANSACTIONS_EXP.COD_TRAN

END

GO

CREATE PROCEDURE SP_REG_RECONCILE_INVALID(@TP TP_INVALID_TRANSACTION READONLY)    
AS    
BEGIN  
  
UPDATE RECONCILE_TRAN_INVALID  
SET ACTIVE = 0  
FROM RECONCILE_TRAN_INVALID  
JOIN @TP TP  
 ON TP.COD_AC = RECONCILE_TRAN_INVALID.COD_AC  
 AND TP.RECONCILE_DATE = RECONCILE_TRAN_INVALID.RECONCILE_DATE  
WHERE RECONCILE_TRAN_INVALID.ACTIVE = 1  
  
INSERT INTO RECONCILE_TRAN_INVALID (FILE_NAME, COD_AC, NSU_EXT, AUTH_CODE, BRAND, AMOUNT, TRANSACTION_DATE, PAN,  
NET_AMOUNT, PAGSEGURO_CODE)  
 SELECT  
  FILE_NAME  
    ,COD_AC  
    ,NSU_EXT  
    ,AUTH_CODE  
    ,BRAND  
    ,AMOUNT  
    ,TRAN_DATE  
    ,PAN  
    ,NET_AMOUNT  
	,PAGSEGURO_CODE
 FROM @TP;  
END