IF OBJECT_ID('SP_GW_LS_DETAILS_PLAN') IS NOT NULL DROP PROCEDURE SP_GW_LS_DETAILS_PLAN
GO
CREATE PROCEDURE [dbo].[SP_GW_LS_DETAILS_PLAN]         
/*----------------------------------------------------------------------------------------        
Procedure Name: [SP_GW_LS_DETAILS_PLAN]      Project.......: TKPP        
    
Description: Same as SP_GW_LS_DETAILS_PLAN, but bundling online and face-to-face fees together    
    
------------------------------------------------------------------------------------------        
Author                          VERSION        Date                            Description        
------------------------------------------------------------------------------------------        
Marcus Gall                       V1         17/06/2020                          Creation        
------------------------------------------------------------------------------------------*/       
(    
 @COD_PLAN INT,    
 @COD_AFFILIATOR INT    
)    
AS    
BEGIN
    
 DECLARE @COD_AFF_PLAN INT;

SELECT
	@COD_AFF_PLAN = COD_AFFILIATOR
FROM [PLAN]
WHERE COD_PLAN = @COD_PLAN
AND ACTIVE = 1;

IF (@COD_AFF_PLAN <> @COD_AFFILIATOR)
THROW 61064, 'INVALID PLAN FOR THIS AFFILIATOR OR PLAN IS INACTIVE', 1;



SELECT
	PLANS.COD_PLAN
   ,PLANS.[NAME_PLAN]
   ,PLANS.[DESCRIPTION]
   ,PLANS.CATEGORY
   ,PLANS.TYPE_PLAN
   ,PLANS.BRAND_GROUP
   ,PLANS.TRANSACTION_TYPE
   ,PLANS.QTY_INI_PLOTS
   ,PLANS.QTY_FINAL_PLOTS
   ,SUM(PLANS.ANTICIPATION_PERCENTAGE) AS ANTICIPATION_PERCENTAGE
   ,SUM(INTERVAL_DEBIT) AS INTERVAL_DEBIT
   ,SUM(INTERVAL_CREDIT_A_VISTA) AS INTERVAL_CREDIT_A_VISTA
   ,SUM(INTERVAL_CREDIT_PARCELADO) AS INTERVAL_CREDIT_PARCELADO
   ,SUM(INTERVAL_ONLINE) AS INTERVAL_ONLINE
   ,SUM(PLANS.PARCENTAGE) AS PARCENTAGE
   ,SUM(PLANS.RATE) AS RATE
   ,PLANS.PLAN_OPTION AS PLAN_OPTION
   ,PLANS.EQUIPMENT_MODEL
FROM (SELECT
		[PLAN].COD_PLAN
	   ,[PLAN].CODE AS [NAME_PLAN]
	   ,[PLAN].[DESCRIPTION]
	   ,PLAN_CATEGORY.CATEGORY
	   ,TYPE_PLAN.CODE AS TYPE_PLAN
	   ,BRAND.[GROUP] AS BRAND_GROUP
	   ,TRANSACTION_TYPE.CODE AS TRANSACTION_TYPE
	   ,TAX_PLAN.QTY_INI_PLOTS
	   ,TAX_PLAN.QTY_FINAL_PLOTS
	   ,CASE
			WHEN (SOURCE_TRANSACTION.COD_SOURCE_TRAN = 1) THEN 'SITE'
			ELSE EQUIPMENT_MODEL.CODIGO
		END AS EQUIPMENT_MODEL
	   ,TAX_PLAN.ANTICIPATION_PERCENTAGE
	   ,CASE

			WHEN TAX_PLAN.QTY_INI_PLOTS = 1 AND
				TAX_PLAN.QTY_FINAL_PLOTS = 1 AND
				TAX_PLAN.COD_TTYPE = 2 AND
				SOURCE_TRANSACTION.COD_SOURCE_TRAN = 2 THEN TAX_PLAN.INTERVAL

			ELSE 0
		END AS [INTERVAL_DEBIT]
	   ,CASE
			WHEN TAX_PLAN.QTY_INI_PLOTS = 1 AND
				TAX_PLAN.QTY_FINAL_PLOTS = 1 AND
				TAX_PLAN.COD_TTYPE = 1 AND

				SOURCE_TRANSACTION.COD_SOURCE_TRAN = 2 THEN TAX_PLAN.INTERVAL
			ELSE 0
		END AS [INTERVAL_CREDIT_A_VISTA]
	   ,CASE
			WHEN TAX_PLAN.QTY_INI_PLOTS >= 1 AND
				TAX_PLAN.QTY_FINAL_PLOTS > 1 AND
				TAX_PLAN.COD_TTYPE = 1 AND
				SOURCE_TRANSACTION.COD_SOURCE_TRAN = 2 THEN TAX_PLAN.INTERVAL
			ELSE 0
		END AS [INTERVAL_CREDIT_PARCELADO]
	   ,CASE

			WHEN SOURCE_TRANSACTION.COD_SOURCE_TRAN = 1 THEN TAX_PLAN.INTERVAL
			ELSE 0
		END AS [INTERVAL_ONLINE]
	   ,PARCENTAGE
	   ,RATE
	   ,CASE
			WHEN TAX_PLAN.COD_MODEL IS NOT NULL THEN 'TERMINAL_PLAN'
			ELSE NULL
		END AS PLAN_OPTION
	FROM [PLAN]
	JOIN TAX_PLAN
		ON TAX_PLAN.COD_PLAN = [PLAN].COD_PLAN
	JOIN PLAN_CATEGORY
		ON PLAN_CATEGORY.COD_PLAN_CATEGORY = [PLAN].COD_PLAN_CATEGORY

	JOIN TYPE_PLAN
		ON TYPE_PLAN.COD_T_PLAN = [PLAN].COD_T_PLAN
	JOIN TRANSACTION_TYPE
		ON TRANSACTION_TYPE.COD_TTYPE = TAX_PLAN.COD_TTYPE
	JOIN BRAND
		ON BRAND.COD_BRAND = TAX_PLAN.COD_BRAND

	JOIN SOURCE_TRANSACTION
		ON SOURCE_TRANSACTION.COD_SOURCE_TRAN = TAX_PLAN.COD_SOURCE_TRAN
	JOIN AFFILIATOR
		ON AFFILIATOR.COD_AFFILIATOR = [PLAN].COD_AFFILIATOR
	LEFT JOIN EQUIPMENT_MODEL
		ON EQUIPMENT_MODEL.COD_MODEL = TAX_PLAN.COD_MODEL
	--LEFT JOIN PLAN_OPTION
	--    ON PLAN_OPTION.COD_PLAN_OPT = [PLAN].COD_PLAN_OPT
	WHERE TAX_PLAN.ACTIVE = 1) AS PLANS
WHERE PLANS.COD_PLAN = @COD_PLAN
GROUP BY PLANS.COD_PLAN
		,PLANS.[NAME_PLAN]
		,PLANS.[DESCRIPTION]
		,PLANS.CATEGORY
		,PLANS.TYPE_PLAN
		,PLANS.BRAND_GROUP
		,PLANS.TRANSACTION_TYPE
		,PLANS.QTY_INI_PLOTS
		,PLANS.QTY_FINAL_PLOTS
		,PLANS.PLAN_OPTION
		,PLANS.EQUIPMENT_MODEL
END

GO

GO
 

IF OBJECT_ID('SP_GW_LS_DETAILS_PLAN_ESTABLISHMENT') IS NOT NULL
DROP PROCEDURE [SP_GW_LS_DETAILS_PLAN_ESTABLISHMENT];

GO
CREATE PROCEDURE [dbo].[SP_GW_LS_DETAILS_PLAN_ESTABLISHMENT]
/*----------------------------------------------------------------------------------------          
Procedure Name: [SP_GW_LS_DETAILS_PLAN_ESTABLISHMENT]    Project.......: TKPP          
------------------------------------------------------------------------------------------          
Author                          VERSION        Date                            Description          
------------------------------------------------------------------------------------------          
Marcus Gall                       V1         19/06/2020                          Creation        
Caike uchoa                       v2         25/11/2020                        add corre??o cod_opt_plan
------------------------------------------------------------------------------------------*/ (@COD_EC INT,
@COD_AFFILIATOR INT)
AS
BEGIN

 



    IF ( SELECT
		COUNT(*)
	FROM [PLAN]
	JOIN ASS_TAX_DEPART
		ON ASS_TAX_DEPART.COD_PLAN = [PLAN].COD_PLAN
	JOIN PLAN_CATEGORY
		ON PLAN_CATEGORY.COD_PLAN_CATEGORY = [PLAN].COD_PLAN_CATEGORY
	JOIN TYPE_PLAN
		ON TYPE_PLAN.COD_T_PLAN = [PLAN].COD_T_PLAN
	JOIN TRANSACTION_TYPE
		ON TRANSACTION_TYPE.COD_TTYPE = ASS_TAX_DEPART.COD_TTYPE
	JOIN BRAND
		ON BRAND.COD_BRAND = ASS_TAX_DEPART.COD_BRAND
	JOIN SOURCE_TRANSACTION
		ON SOURCE_TRANSACTION.COD_SOURCE_TRAN = ASS_TAX_DEPART.COD_SOURCE_TRAN
	JOIN DEPARTMENTS_BRANCH
		ON DEPARTMENTS_BRANCH.COD_DEPTO_BRANCH = ASS_TAX_DEPART.COD_DEPTO_BRANCH
	JOIN BRANCH_EC
		ON BRANCH_EC.COD_BRANCH = DEPARTMENTS_BRANCH.COD_BRANCH
	JOIN COMMERCIAL_ESTABLISHMENT
		ON COMMERCIAL_ESTABLISHMENT.COD_EC = BRANCH_EC.COD_EC
	JOIN AFFILIATOR
		ON AFFILIATOR.COD_AFFILIATOR = COMMERCIAL_ESTABLISHMENT.COD_AFFILIATOR
	WHERE COMMERCIAL_ESTABLISHMENT.COD_EC = @COD_EC
	AND ASS_TAX_DEPART.ACTIVE = 1)
= 0
THROW 61067, 'THIS ESTABLISHMENT DOES NOT HAVE AN ASSOCIATED PLAN', 1;




SELECT
	PLANS.COD_PLAN
   ,PLANS.[NAME_PLAN]
   ,PLANS.[DESCRIPTION]
   ,PLANS.CATEGORY
   ,PLANS.TYPE_PLAN
   ,PLANS.BRAND_GROUP
   ,PLANS.TRANSACTION_TYPE
   ,PLANS.QTY_INI_PLOTS
   ,PLANS.QTY_FINAL_PLOTS
   ,SUM(PLANS.ANTICIPATION_PERCENTAGE) AS ANTICIPATION_PERCENTAGE
   ,SUM(INTERVAL_DEBIT) AS INTERVAL_DEBIT
   ,SUM(INTERVAL_CREDIT_A_VISTA) AS INTERVAL_CREDIT_A_VISTA
   ,SUM(INTERVAL_CREDIT_PARCELADO) AS INTERVAL_CREDIT_PARCELADO
   ,SUM(INTERVAL_ONLINE) AS INTERVAL_ONLINE
   ,SUM(PLANS.PARCENTAGE) AS PARCENTAGE
   ,SUM(PLANS.RATE) AS RATE
   ,PLANS.PLAN_OPTION AS PLAN_OPTION
   ,PLANS.EQUIPMENT_MODEL
FROM (SELECT
		COMMERCIAL_ESTABLISHMENT.COD_EC
	   ,[PLAN].COD_PLAN
	   ,[PLAN].CODE AS [NAME_PLAN]
	   ,[PLAN].[DESCRIPTION]
	   ,PLAN_CATEGORY.CATEGORY
	   ,TYPE_PLAN.CODE AS TYPE_PLAN
	   ,BRAND.[GROUP] AS BRAND_GROUP
	   ,TRANSACTION_TYPE.CODE AS TRANSACTION_TYPE
	   ,ASS_TAX_DEPART.QTY_INI_PLOTS
	   ,ASS_TAX_DEPART.QTY_FINAL_PLOTS
	   ,CASE
			WHEN (SOURCE_TRANSACTION.COD_SOURCE_TRAN = 1) THEN 'SITE'
			ELSE EQUIPMENT_MODEL.CODIGO
		END AS EQUIPMENT_MODEL
	   ,ASS_TAX_DEPART.ANTICIPATION_PERCENTAGE
	   ,CASE
			WHEN ASS_TAX_DEPART.QTY_INI_PLOTS = 1 AND
				ASS_TAX_DEPART.QTY_FINAL_PLOTS = 1 AND
				ASS_TAX_DEPART.COD_TTYPE = 2 AND
				SOURCE_TRANSACTION.COD_SOURCE_TRAN = 2 THEN ASS_TAX_DEPART.INTERVAL
			ELSE 0
		END AS [INTERVAL_DEBIT]
	   ,CASE
			WHEN ASS_TAX_DEPART.QTY_INI_PLOTS = 1 AND
				ASS_TAX_DEPART.QTY_FINAL_PLOTS = 1 AND
				ASS_TAX_DEPART.COD_TTYPE = 1 AND
				SOURCE_TRANSACTION.COD_SOURCE_TRAN = 2 THEN ASS_TAX_DEPART.INTERVAL
			ELSE 0
		END AS [INTERVAL_CREDIT_A_VISTA]
	   ,CASE
			WHEN ASS_TAX_DEPART.QTY_INI_PLOTS >= 1 AND
				ASS_TAX_DEPART.QTY_FINAL_PLOTS > 1 AND
				ASS_TAX_DEPART.COD_TTYPE = 1 AND
				SOURCE_TRANSACTION.COD_SOURCE_TRAN = 2 THEN ASS_TAX_DEPART.INTERVAL
			ELSE 0
		END AS [INTERVAL_CREDIT_PARCELADO]
	   ,CASE
			WHEN SOURCE_TRANSACTION.COD_SOURCE_TRAN = 1 THEN ASS_TAX_DEPART.INTERVAL
			ELSE 0
		END AS [INTERVAL_ONLINE]
	   ,PARCENTAGE
	   ,RATE
	   ,CASE
			WHEN ASS_TAX_DEPART.COD_MODEL IS NOT NULL THEN 'TERMINAL_PLAN'
			ELSE NULL
		END AS PLAN_OPTION
	FROM [PLAN]
	JOIN ASS_TAX_DEPART
		ON ASS_TAX_DEPART.COD_PLAN = [PLAN].COD_PLAN
	JOIN PLAN_CATEGORY
		ON PLAN_CATEGORY.COD_PLAN_CATEGORY = [PLAN].COD_PLAN_CATEGORY
	JOIN TYPE_PLAN
		ON TYPE_PLAN.COD_T_PLAN = [PLAN].COD_T_PLAN
	JOIN TRANSACTION_TYPE
		ON TRANSACTION_TYPE.COD_TTYPE = ASS_TAX_DEPART.COD_TTYPE
	JOIN BRAND
		ON BRAND.COD_BRAND = ASS_TAX_DEPART.COD_BRAND
	JOIN SOURCE_TRANSACTION
		ON SOURCE_TRANSACTION.COD_SOURCE_TRAN = ASS_TAX_DEPART.COD_SOURCE_TRAN
	JOIN DEPARTMENTS_BRANCH
		ON DEPARTMENTS_BRANCH.COD_DEPTO_BRANCH = ASS_TAX_DEPART.COD_DEPTO_BRANCH
	JOIN BRANCH_EC
		ON BRANCH_EC.COD_BRANCH = DEPARTMENTS_BRANCH.COD_BRANCH
	JOIN COMMERCIAL_ESTABLISHMENT
		ON COMMERCIAL_ESTABLISHMENT.COD_EC = BRANCH_EC.COD_EC
	JOIN AFFILIATOR
		ON AFFILIATOR.COD_AFFILIATOR = COMMERCIAL_ESTABLISHMENT.COD_AFFILIATOR
	LEFT JOIN EQUIPMENT_MODEL
		ON EQUIPMENT_MODEL.COD_MODEL = ASS_TAX_DEPART.COD_MODEL
	--LEFT JOIN PLAN_OPTION
	--    ON PLAN_OPTION.COD_PLAN_OPT = [PLAN].COD_PLAN_OPT
	WHERE ASS_TAX_DEPART.ACTIVE = 1) AS PLANS
WHERE PLANS.COD_EC = @COD_EC
GROUP BY PLANS.COD_PLAN
		,PLANS.[NAME_PLAN]
		,PLANS.[DESCRIPTION]
		,PLANS.CATEGORY
		,PLANS.TYPE_PLAN
		,PLANS.BRAND_GROUP
		,PLANS.TRANSACTION_TYPE
		,PLANS.QTY_INI_PLOTS
		,PLANS.QTY_FINAL_PLOTS
		,PLANS.PLAN_OPTION
		,PLANS.EQUIPMENT_MODEL
END