

SELECT
	REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(PATH_DOC, 'C:\', 'E:\'), 'E:\\TKPP-NC\\DOCS\\\\', 'E:\OPERATION_FILES\DOCS\'), 'E:\DOCS\', 'E:\OPERATION_FILES\DOCS\'), 'E:\TKPP-NC\DOCS\\', 'E:\OPERATION_FILES\DOCS\'), 'E:\TKPP-NC\DOCS\', 'E:\OPERATION_FILES\DOCS\')
FROM DOCS_BRANCH
INNER JOIN BRANCH_EC
	ON BRANCH_EC.COD_BRANCH = DOCS_BRANCH.COD_BRANCH
INNER JOIN COMMERCIAL_ESTABLISHMENT
	ON COMMERCIAL_ESTABLISHMENT.COD_EC = BRANCH_EC.COD_EC
WHERE DOCS_BRANCH.ACTIVE = 1
AND PATH_DOC IS NOT NULL
ORDER BY PATH_DOC

GO

SELECT
	REPLACE(DOCUMENTS, 'C:\Afiliador', 'E:\OPERATION_FILES\AFFILIATOR\DOCS')
FROM DOCS_AFFILIATOR
WHERE ACTIVE = 1

GO

SELECT
	--REPLACE(LOGO_AFFILIATE, 'C:\Afiliador', 'E:\OPERATION_FILES\AFFILIATOR\THEMES')
	REPLACE(LOGO_AFFILIATE, 'C:\Afiliador', 'E:\OPERATION_FILES\AFFILIATOR\THEMES')
   ,REPLACE(LOGO_HEADER_AFFILIATE, 'C:\Afiliador', 'E:\OPERATION_FILES\AFFILIATOR\THEMES')
   ,REPLACE(BACKGROUND_IMAGE, 'C:\Afiliador', 'E:\OPERATION_FILES\AFFILIATOR\THEMES')
FROM THEMES
WHERE ACTIVE = 1