CREATE PROCEDURE SP_FD_DATA_RECONCILE_FIN(@INITIAL_DATE DATE,    
                                          @FINAL_DATE DATE,    
                                          @ACQCODE varchar(255))    
AS    
BEGIN
  
    
    DECLARE @INITIAL DATETIME2 = convert(datetime, @INITIAL_DATE, 103);
  
    
    DECLARE @FINAL DATETIME2 = DATEADD(MS, -1, DATEADD(D, 1, CONVERT(DATETIME2, @FINAL_DATE)))

SELECT
	T.COD_TRAN
   ,T.CODE AS TRANSACTION_CODE
   ,T.BRAZILIAN_DATE AS TRANSACTION_DATE
   ,T.AMOUNT AS TRANSACTION_AMOUNT
   ,T.PLOTS
   ,T.BRAND
   ,IIF(ASSIGN_DATA.NEW_PREVISION IS NOT NULL, ASSIGN_DATA.NEW_PREVISION, TT.PREVISION_RECEIVE_DATE) AS PrevisionPayment
   ,([t].AMOUNT - ([t].AMOUNT * ISNULL(tr.TAX_VALUE, ASS_TR_TYPE_COMP.TAX_VALUE) / 100)) / [t].PLOTS AS NET_AMOUNT
   ,TT.PLOT
   ,[TRANSACTION_DATA_EXT].[NAME] AS [TRAN_DATA_EXT]
   ,[TRANSACTION_DATA_EXT].[VALUE] AS [TRAN_DATA_EXT_VALUE]
   ,(SELECT
			[TDE].[VALUE]
		FROM [TRANSACTION_DATA_EXT] TDE WITH (NOLOCK)
		WHERE [TDE].[COD_TRAN] = [T].[COD_TRAN]
		AND [TDE].[NAME] = 'AUTHCODE')
	AS AUTHCODE
   ,T.COD_SITUATION
   ,ACQUIRER.CODE AS ACQ_CODE
   ,T.LOGICAL_NUMBER_ACQ
   ,DATA_TID_AVAILABLE_EC.COD_AC
   ,t.PAN
   ,tt.COD_TITLE
   ,tt.IS_FIN_REC
   ,TRANSACTION_TYPE.CODE AS TYPE_TRAN
FROM [TRANSACTION](NOLOCK) T
JOIN [TRANSACTION_TITLES](NOLOCK) TT
	ON TT.COD_TRAN = T.COD_TRAN
JOIN DATA_TID_AVAILABLE_EC
	ON DATA_TID_AVAILABLE_EC.TID = [T].LOGICAL_NUMBER_ACQ
		AND DATA_TID_AVAILABLE_EC.ACTIVE = 1
JOIN ACQUIRER
	ON DATA_TID_AVAILABLE_EC.COD_AC = ACQUIRER.COD_AC
JOIN ASS_TR_TYPE_COMP
	ON [t].COD_ASS_TR_COMP = ASS_TR_TYPE_COMP.COD_ASS_TR_COMP
LEFT JOIN ASS_TR_TYPE_COMP tr
	ON tr.COD_AC = ACQUIRER.COD_AC
		AND tr.COD_TTYPE = ASS_TR_TYPE_COMP.COD_TTYPE
		AND tr.COD_BRAND = ASS_TR_TYPE_COMP.COD_BRAND
		AND tr.COD_SOURCE_TRAN = ASS_TR_TYPE_COMP.COD_SOURCE_TRAN
		AND tr.PLOT_INI = ASS_TR_TYPE_COMP.PLOT_INI
		AND tr.PLOT_END = ASS_TR_TYPE_COMP.PLOT_END
LEFT JOIN [TRANSACTION_DATA_EXT] WITH (NOLOCK)
	ON [TRANSACTION_DATA_EXT].[COD_TRAN] = [T].[COD_TRAN]
LEFT JOIN ASSIGN_DATA
	ON ASSIGN_DATA.COD_TITLE = TT.COD_TITLE
JOIN TRANSACTION_TYPE
	ON TRANSACTION_TYPE.COD_TTYPE = T.COD_TTYPE
WHERE T.COD_SITUATION IN (3, 6, 22, 14)
AND COALESCE([TRANSACTION_DATA_EXT].[NAME], '0') IN ('NSU', 'RCPTTXID', 'AUTO', '0')
AND T.BRAZILIAN_DATE BETWEEN @INITIAL AND @FINAL
AND ACQUIRER.CODE = @ACQCODE
--AND TRANSACTION_DATA_EXT.[VALUE] = '214061'  
--AND T.COD_TRAN = 8060961
UNION ALL
SELECT
	T.COD_TRAN
   ,T.CODE AS TRANSACTION_CODE
   ,T.BRAZILIAN_DATE AS TRANSACTION_DATE
   ,T.AMOUNT AS TRANSACTION_AMOUNT
   ,T.PLOTS
   ,T.BRAND
   ,IIF(ASSIGN_DATA.NEW_PREVISION IS NOT NULL, ASSIGN_DATA.NEW_PREVISION, TT.PREVISION_RECEIVE_DATE) AS PrevisionPayment
   ,([t].AMOUNT - ([t].AMOUNT * ISNULL(tr.TAX_VALUE, ASS_TR_TYPE_COMP.TAX_VALUE) / 100)) / [t].PLOTS AS NET_AMOUNT
   ,TT.PLOT
   ,[TRANSACTION_DATA_EXT].[NAME] AS [TRAN_DATA_EXT]
   ,[TRANSACTION_DATA_EXT].[VALUE] AS [TRAN_DATA_EXT_VALUE]
   ,(SELECT
			[TDE].[VALUE]
		FROM [TRANSACTION_DATA_EXT] TDE WITH (NOLOCK)
		WHERE [TDE].[COD_TRAN] = [T].[COD_TRAN]
		AND [TDE].[NAME] = 'AUTHCODE')
	AS AUTHCODE
   ,T.COD_SITUATION
   ,ACQUIRER.CODE AS ACQ_CODE
   ,T.LOGICAL_NUMBER_ACQ
   ,ACQUIRER.COD_AC
   ,t.PAN
   ,tt.COD_TITLE
   ,tt.IS_FIN_REC
   ,TRANSACTION_TYPE.CODE AS TYPE_TRAN
FROM [TRANSACTION](NOLOCK) T
JOIN [TRANSACTION_TITLES](NOLOCK) TT
	ON TT.COD_TRAN = T.COD_TRAN
JOIN [ASS_TR_TYPE_COMP]
	ON [ASS_TR_TYPE_COMP].[COD_ASS_TR_COMP] = [T].[COD_ASS_TR_COMP]
JOIN [ACQUIRER]
	ON [ACQUIRER].[COD_AC] = [ASS_TR_TYPE_COMP].[COD_AC]
		AND ACQUIRER.COD_AC = 25
LEFT JOIN [TRANSACTION_DATA_EXT] WITH (NOLOCK)
	ON [TRANSACTION_DATA_EXT].[COD_TRAN] = [T].[COD_TRAN]
LEFT JOIN ASS_TR_TYPE_COMP tr
	ON tr.COD_AC = ACQUIRER.COD_AC
		AND tr.COD_TTYPE = ASS_TR_TYPE_COMP.COD_TTYPE
		AND tr.COD_BRAND = ASS_TR_TYPE_COMP.COD_BRAND
		AND tr.COD_SOURCE_TRAN = ASS_TR_TYPE_COMP.COD_SOURCE_TRAN
		AND tr.PLOT_INI = ASS_TR_TYPE_COMP.PLOT_INI
		AND tr.PLOT_END = ASS_TR_TYPE_COMP.PLOT_END
LEFT JOIN ASSIGN_DATA
	ON ASSIGN_DATA.COD_TITLE = TT.COD_TITLE
JOIN TRANSACTION_TYPE
	ON TRANSACTION_TYPE.COD_TTYPE = T.COD_TTYPE
WHERE T.COD_SITUATION IN (3, 6, 22, 14)
AND COALESCE([TRANSACTION_DATA_EXT].[NAME], '0') IN ('NSU', 'RCPTTXID', 'AUTO', '0')
AND T.BRAZILIAN_DATE BETWEEN @INITIAL AND @FINAL
AND ACQUIRER.CODE = @ACQCODE
--AND TRANSACTION_DATA_EXT.[VALUE] = '214061'  
--AND T.COD_TRAN = 8060961
END