--DEFINIÇÃO DE VARIAVEIS USADAS PARA A VALIDAÇÃO

DECLARE @COD_EC INT;
DECLARE @COD_EQUIP INT;
DECLARE @COD_AFFILIATOR INT;

SELECT
	@COD_EC = COD_EC
   ,@COD_AFFILIATOR = COD_AFFILIATOR
   ,@COD_EQUIP = COD_EQUIP
FROM VW_COMPANY_EC_AFF_BR_DEP_EQUIP
WHERE SERIAL = '68030421'


--SOMENTE PARCELADO CLIENTE
INSERT INTO PRODUCTS_UNAVAILABLE_EC (COD_EC, COD_AFFILIATOR, IS_SIMULATED, NOT_SIMULATED, PRODUCTS_CUSTOMIZED) VALUES (@COD_EC, NULL, 1, 0, 0);