--DEFINIÇÃO DE VARIAVEIS USADAS PARA A VALIDAÇÃO

DECLARE @COD_EC INT;
DECLARE @COD_EQUIP INT;
DECLARE @COD_AFF INT;

SELECT TOP 1
	@COD_EC = COD_EC
   ,@COD_AFF = COD_AFFILIATOR
   ,@COD_EQUIP = COD_EQUIP
FROM VW_COMPANY_EC_AFF_BR_DEP_EQUIP
WHERE COD_EQUIP = 3;


----WITH [CTE_BLOCKED_AFF]
----AS
----(SELECT
----		AUX
----	FROM PRODUCTS_UNAVAILABLE_EC
----	WHERE COD_AFFILIATOR = @COD_AFF
----	EXCEPT
----	SELECT
----		AUX
----	FROM PRODUCTS_UNAVAILABLE_EC
----	WHERE COD_EC = @COD_EC),
----[CTE_BLOCKED_EC]
----AS
----(SELECT
----		AUX
----	FROM PRODUCTS_UNAVAILABLE_EC
----	WHERE COD_EC = @COD_EC)
----SELECT
----	PRODUCTS_UNAVAILABLE_EC.COD_PR_UN_EC
----   ,PRODUCTS_UNAVAILABLE_EC.IS_SIMULATED
----   ,PRODUCTS_UNAVAILABLE_EC.PRODUCTS_CUSTOMIZED
----   ,PRODUCTS_UNAVAILABLE_EC.NOT_SIMULATED
----   ,PRODUCTS_UNAVAILABLE_EC.COD_EC
----   ,PRODUCTS_UNAVAILABLE_EC.COD_AFFILIATOR
----   ,CUSTOMIZED_UNAVAILABLE_PRODUCTS.COD_PR_ACQ
----   ,CUSTOMIZED_UNAVAILABLE_PRODUCTS.COD_MODEL
------INTO #PRODUCTS_TO_ASSOCIATE
----FROM [CTE_BLOCKED_AFF]
----JOIN PRODUCTS_UNAVAILABLE_EC
----	ON CTE_BLOCKED_AFF.AUX = PRODUCTS_UNAVAILABLE_EC.AUX
----LEFT JOIN CUSTOMIZED_UNAVAILABLE_PRODUCTS
----	ON CUSTOMIZED_UNAVAILABLE_PRODUCTS.COD_PR_UN_EC = PRODUCTS_UNAVAILABLE_EC.COD_PR_UN_EC
----WHERE PRODUCTS_UNAVAILABLE_EC.COD_AFFILIATOR = @COD_AFF
----UNION
----SELECT
----	PRODUCTS_UNAVAILABLE_EC.COD_PR_UN_EC
----   ,PRODUCTS_UNAVAILABLE_EC.IS_SIMULATED
----   ,PRODUCTS_UNAVAILABLE_EC.PRODUCTS_CUSTOMIZED
----   ,PRODUCTS_UNAVAILABLE_EC.NOT_SIMULATED
----   ,PRODUCTS_UNAVAILABLE_EC.COD_EC
----   ,PRODUCTS_UNAVAILABLE_EC.COD_AFFILIATOR
----   ,CUSTOMIZED_UNAVAILABLE_PRODUCTS.COD_PR_ACQ
----   ,CUSTOMIZED_UNAVAILABLE_PRODUCTS.COD_MODEL
----FROM [CTE_BLOCKED_EC]
----JOIN PRODUCTS_UNAVAILABLE_EC
----	ON CTE_BLOCKED_EC.AUX = PRODUCTS_UNAVAILABLE_EC.AUX
----LEFT JOIN CUSTOMIZED_UNAVAILABLE_PRODUCTS
----	ON CUSTOMIZED_UNAVAILABLE_PRODUCTS.COD_PR_UN_EC = PRODUCTS_UNAVAILABLE_EC.COD_PR_UN_EC
----WHERE PRODUCTS_UNAVAILABLE_EC.COD_EC = @COD_EC;







------SOMENTE PARCELADO CLIENTE
----IF ( SELECT
----		COUNT(*)
----	FROM PRODUCTS_UNAVAILABLE_EC
----	WHERE COD_EC = @COD_EC)
----= 0
----INSERT INTO PRODUCTS_UNAVAILABLE_EC (COD_EC, COD_AFFILIATOR, IS_SIMULATED, NOT_SIMULATED, PRODUCTS_CUSTOMIZED)
----	VALUES (@COD_EC, NULL, 1, 0, 0);

----SOMENTE COMUM
--UPDATE PRODUCTS_UNAVAILABLE_EC
--SET IS_SIMULATED = 0
--   ,NOT_SIMULATED = 1
--WHERE COD_EC = @COD_EC

----PARCIAL
--UPDATE PRODUCTS_UNAVAILABLE_EC
--SET IS_SIMULATED = 1
--   ,NOT_SIMULATED = 1
--   ,PRODUCTS_CUSTOMIZED = 0
--WHERE COD_EC = @COD_EC

----INSERT INTO CUSTOMIZED_UNAVAILABLE_PRODUCTS (COD_PR_UN_EC, COD_PR_ACQ)
----	VALUES (1, 50),
----	(1, 51),
----	(1, 52),
----	(1, 53),
----	(1, 54),
----	(1, 55),
----	(1, 56),
----	(1, 57)A
----INSERT INTO CUSTOMIZED_UNAVAILABLE_PRODUCTS (COD_PR_UN_EC, COD_PR_ACQ)
----	VALUES (1, 58),
----	(1, 60),
----	(1, 61),
----	(1, 77),
----	(1, 78),
----	(1, 79),
----	(1, 80),
----	(1, 85),
----	(1, 87),
----	(1, 89),
----	(1, 91),
----	(1, 92),
----	(1, 93),
----	(1, 94),
----	(1, 465),
----	(1, 509),
----	(1, 510),
----	(1, 511),
----	(1, 512),
----	(1, 513),
----	(1, 514),
----	(1, 600),
----	(1, 601),
----	(1, 602)





----AFILIADOR - SOMENTE PARCELADO
--IF ( SELECT
--		COUNT(*)
--	FROM PRODUCTS_UNAVAILABLE_EC
--	WHERE COD_AFFILIATOR = @COD_AFF)
--= 0
--INSERT INTO PRODUCTS_UNAVAILABLE_EC (COD_EC, COD_AFFILIATOR, IS_SIMULATED, NOT_SIMULATED, PRODUCTS_CUSTOMIZED)
--	VALUES (NULL, @COD_AFF, 1, 0, 0);

----AFILIADOR - SOMENTE COMUM
----UPDATE PRODUCTS_UNAVAILABLE_EC
----SET IS_SIMULATED = 0
----   ,NOT_SIMULATED = 1
----WHERE COD_AFFILIATOR = @COD_AFF

----SELECT
----	*
----FROM PRODUCTS_UNAVAILABLE_EC
----DELETE FROM PRODUCTS_UNAVAILABLE_EC
----WHERE COD_EC IS NOT NULL



----AFILIADOR - PARCIAL
--UPDATE PRODUCTS_UNAVAILABLE_EC
--SET IS_SIMULATED = 1
--   ,NOT_SIMULATED = 1
--   ,PRODUCTS_CUSTOMIZED = 1
--WHERE COD_AFFILIATOR = @COD_AFF


--INSERT INTO CUSTOMIZED_UNAVAILABLE_PRODUCTS (COD_PR_UN_EC, COD_PR_ACQ)
--VALUES
--(4, 50 ),
--(4, 52 ),
--(4, 53 ),
--(4, 54 ),
--(4, 56 ),
--(4, 57 ),
--(4, 58 ),
--(4, 60 ),
--(4, 61 ),
--(4, 77 ),
--(4, 78 ),
--(4, 79 ),
--(4, 80 ),
--(4, 85 ),
--(4, 87 ),
--(4, 89 ),
--(4, 91 ),
--(4, 92 ),
--(4, 93 ),
--(4, 94 ),
--(4, 465),
--(4, 509),
--(4, 510),
--(4, 511),
--(4, 512),
--(4, 513),
--(4, 514),
--(4, 600),
--(4, 601),
--(4, 602)

--


--DUPLICADO
IF ( SELECT
		COUNT(*)
	FROM PRODUCTS_UNAVAILABLE_EC
	WHERE COD_EC = @COD_EC)
= 0
INSERT INTO PRODUCTS_UNAVAILABLE_EC (COD_EC, COD_AFFILIATOR, IS_SIMULATED, NOT_SIMULATED, PRODUCTS_CUSTOMIZED)
	VALUES (@COD_EC, NULL, 1, 0, 0);

UPDATE PRODUCTS_UNAVAILABLE_EC
SET IS_SIMULATED = 0
   ,NOT_SIMULATED = 1
WHERE COD_EC = @COD_EC


--SELECT
--	*
--FROM PRODUCTS_UNAVAILABLE_EC

EXEC SP_LOAD_TABLES_EQUIP @COD_EQUIP