--Dia 2 (51-100)
ALTER INDEX PK_ROUTE_ACQUIRER ON dbo.ROUTE_ACQUIRER REBUILD
ALTER INDEX PK_TEMP_TOKEN ON dbo.TEMP_TOKEN REBUILD
ALTER INDEX PK__MESSAGIN__5BED5CBC5348CEA8 ON dbo.MESSAGING REBUILD
ALTER INDEX PK_ROUTE_ACQUIRER_HIST ON dbo.ROUTE_ACQUIRER_HIST REBUILD
ALTER INDEX PK_DATA_EQUIPMENT_AC ON dbo.DATA_EQUIPMENT_AC REBUILD
ALTER INDEX IX_DATA_EQUIP_AC_EQUIP_CODE_NAME ON dbo.DATA_EQUIPMENT_AC REBUILD
ALTER INDEX PK_EQUIPMENT ON dbo.EQUIPMENT REBUILD
ALTER INDEX PK_DENIED_ACESS_USER ON dbo.DENIED_ACCESS_USER REBUILD
ALTER INDEX nci_wi_DATA_EQUIPMENT_AC_6D33476A6C3684006D5214B2DCA2946A ON dbo.DATA_EQUIPMENT_AC REBUILD
ALTER INDEX PK_ASS_DEPTO_EQUIP ON dbo.ASS_DEPTO_EQUIP REBUILD
ALTER INDEX PK_HangFire_State ON HangFire."STATE" REBUILD
ALTER INDEX PK_PROVISORY_PASS_USER ON dbo.PROVISORY_PASS_USER REBUILD
ALTER INDEX PK_DATA_TID_AVAILABLE_EC ON dbo.DATA_TID_AVAILABLE_EC REBUILD
ALTER INDEX PK_SERVICE_AVAILABLE_ ON dbo.SERVICES_AVAILABLE REBUILD
ALTER INDEX nci_wi_ASS_DEPTO_EQUIP_27AD443B42362E9A30CAB5D1C28CBE3B ON dbo.ASS_DEPTO_EQUIP REBUILD
ALTER INDEX PK__ASS_CERC__7E1A8F539109A84A ON dbo.ASS_CERC_EC REBUILD
ALTER INDEX UK_SERIAL_COMP_EQUIP ON dbo.EQUIPMENT REBUILD
ALTER INDEX PK_HangFire_Job ON HangFire.Job REBUILD
ALTER INDEX nci_wi_ASS_DEPTO_EQUIP_AF6D7B1A3482A45F80F3343243E9AD65 ON dbo.ASS_DEPTO_EQUIP REBUILD
ALTER INDEX nci_wi_SERVICES_AVAILABLE_F1E1D450B47D770F66FABF18E90E25E1 ON dbo.SERVICES_AVAILABLE REBUILD
ALTER INDEX IX_ASS_DEPTO_EQUIP_COD_EQUIP_ACTIVE ON dbo.ASS_DEPTO_EQUIP REBUILD
ALTER INDEX PK_HangFire_Set ON Schedule."Set" REBUILD
ALTER INDEX IX_HangFire_Set_Score ON Schedule."Set" REBUILD
ALTER INDEX PK_HangFire_JobParameter ON HangFire.JobParameter REBUILD
ALTER INDEX PK_HangFire_State ON Services.STATE REBUILD
ALTER INDEX IX_ASS_CERC_EC_PROCESSED ON dbo.ASS_CERC_EC REBUILD
ALTER INDEX PK__BANK_DET__102412BB2BC3AE3F ON dbo.BANK_DETAILS_CERC_INFO REBUILD
ALTER INDEX PK_HangFire_Set ON Hagnfire.[SET] REBUILD
ALTER INDEX IX_HangFire_Set_Score ON Hagnfire.[SET] REBUILD
ALTER INDEX nci_wi_BANK_DETAILS_CERC_INFO_FF4C2D49DB98B791DE05200D90118012 ON dbo.BANK_DETAILS_CERC_INFO REBUILD
ALTER INDEX PK_HangFire_Hash ON HangFire.Hash REBUILD
ALTER INDEX PK__PAYMENT___056F1DBFD8EAD04D ON dbo.PAYMENT_LINK REBUILD
ALTER INDEX PK_HangFire_Hash ON Schedule.Hash REBUILD
ALTER INDEX PK_HangFire_Job ON Schedule.Job REBUILD
ALTER INDEX PK__CERC_FIL__75CCD2737B76866A ON dbo.CERC_FILE REBUILD
ALTER INDEX IX_HangFire_Set_ExpireAt ON Schedule.[SET] REBUILD
ALTER INDEX PK_HangFire_State ON Schedule.STATE REBUILD
ALTER INDEX IX_BILLET_BARCODE ON dbo.BILLET_TRANSACTION REBUILD
ALTER INDEX PK__ASS_EC_E__FD55B814ED1DF4DD ON dbo.ASS_EC_EXTERNAL_API REBUILD
ALTER INDEX UQ__PAYMENT___AA1D4379E4BB8096 ON dbo.PAYMENT_LINK REBUILD
ALTER INDEX IX_HangFire_Job_StateName ON HangFire.Job REBUILD
ALTER INDEX PK_ITENS_PROG_COST_AFF ON dbo.ITENS_PROG_COST_AFF REBUILD
ALTER INDEX PK__AFFILIAT__E779B969A70A0E6C ON dbo.AFFILIATOR REBUILD
ALTER INDEX IX_HangFire_Job_ExpireAt ON HangFire.Job REBUILD
ALTER INDEX PK_ACCESS_APPAPI ON dbo.ACCESS_APPAPI REBUILD
ALTER INDEX PK_PRODUCTS_ACQUIRER ON dbo.PRODUCTS_ACQUIRER REBUILD
ALTER INDEX PK_ASS_TR_TYPE_COMP ON dbo.ASS_TR_TYPE_COMP REBUILD
ALTER INDEX PK__TMP_PROM__6A7B03B34BF959A4 ON dbo.TMP_PROMOCODE REBUILD
ALTER INDEX PK_HangFire_JobParameter ON Services.JobParameter REBUILD
ALTER INDEX PK_HangFire_JobParameter ON Services.JobParameter REBUILD
ALTER INDEX IX_ACCESS_COMP_LOGIN ON dbo.ACCESS_APPAPI REBUILD
ALTER INDEX PK_HangFire_Job ON Services.Job REBUILD
ALTER INDEX PK__CUSTOMER__1B9850919E675986 ON dbo.CUSTOMER_LINK REBUILD
ALTER INDEX IX_HangFire_Job_StateName ON Schedule.Job REBUILD
ALTER INDEX IX_HangFire_Job_ExpireAt ON Schedule.Job REBUILD
ALTER INDEX UQ_CLIENT_ID ON dbo.ACCESS_APPAPI REBUILD
ALTER INDEX PK_MERCHANTS_INTEGRATION ON dbo.MERCHANTS_INTEGRATION REBUILD
ALTER INDEX PK_PROGRESSIVE_COST_AFFILIATOR ON dbo.PROGRESSIVE_COST_AFFILIATOR REBUILD
ALTER INDEX PK__ASS_PLAN__29EC734A96212CDF ON dbo.ASS_PLAN_TYPE_ESTAB REBUILD
ALTER INDEX PK__ASS_EC_T__579DD62836211A16 ON dbo.ASS_EC_TRAN_PRODUCT REBUILD
ALTER INDEX PK_BANKS ON dbo.BANKS REBUILD
ALTER INDEX PK__SPLIT_PR__952E68B1F73C85C5 ON dbo.SPLIT_PRODUCTS REBUILD
ALTER INDEX IX_HangFire_AggregatedCounter_ExpireAt ON HangFire.AggregatedCounter REBUILD
ALTER INDEX PK_ASS_PARAMS_PRODUCTS ON dbo.ASS_PARAMS_PRODUCTS REBUILD
ALTER INDEX PK__NOTIFICA__23C61893E3389221 ON dbo.NOTIFICATION_MESSAGES REBUILD
ALTER INDEX PK_REGISTER_ARCHIVEELO ON dbo.REGISTER_ARCHIVE_EC_ELO REBUILD
ALTER INDEX IX_HangFire_Server_LastHeartbeat ON Schedule.Server REBUILD
ALTER INDEX IX_HangFire_Server_LastHeartbeat ON HangFire.Server REBUILD
ALTER INDEX IX_HangFire_Server_LastHeartbeat ON Services.Server REBUILD
ALTER INDEX PK__BRANCH_B__CC5737418C5B6F7D ON dbo.BRANCH_BUSINESS REBUILD
ALTER INDEX PK__CELER_PA__21CAFB2C4D087E0B ON dbo.CELER_PAY_REQUEST_HISTORY REORGANIZE
ALTER INDEX PK_EQUIPMENT_LOG ON dbo.EQUIPMENT_LOG REORGANIZE
ALTER INDEX PK__PRODUCTS__AC16B1ED62550BC2 ON dbo.PRODUCTS_LINK REORGANIZE
ALTER INDEX PK_PASS_HISTORY ON dbo.PASS_HISTORY REORGANIZE
ALTER INDEX PK__SHIPPING__6B977C668B292B0B ON dbo.SHIPPING_LINK REORGANIZE
ALTER INDEX PK_OPERATION_COST_AFFILIATOR ON dbo.OPERATION_COST_AFFILIATOR REORGANIZE
ALTER INDEX IX_HangFire_Hash_ExpireAt ON HangFire."Hash" REORGANIZE
ALTER INDEX PK_USERS ON dbo.USERS REORGANIZE
ALTER INDEX UQ_TID_EQUIPMENT ON dbo.EQUIPMENT REORGANIZE
ALTER INDEX IX_HangFire_Set_ExpireAt ON dbo."Set" REORGANIZE
ALTER INDEX un_report_transactions_exp ON dbo.REPORT_TRANSACTIONS_EXP REORGANIZE
ALTER INDEX UQ_CODE_BRANCH_COMPANY ON dbo.BRANCH_EC REORGANIZE
ALTER INDEX IX_REP_TRAN_EXP_COD_TRAN ON dbo.REPORT_TRANSACTIONS_EXP REORGANIZE
ALTER INDEX IX_BRANCH_COD_TYPE_RECEIVE ON dbo.BRANCH_EC REORGANIZE
ALTER INDEX IX_REP_EXP_ON_SIT_IC_TRANCODE_CANCEL ON dbo.REPORT_TRANSACTIONS_EXP REORGANIZE
ALTER INDEX UQ_CODE_COMMERCIAL_ESTABLISHMENT ON dbo.COMMERCIAL_ESTABLISHMENT REORGANIZE
ALTER INDEX UQ_SEGMENTS ON dbo.SEGMENTS REORGANIZE
ALTER INDEX un_report_transactions ON dbo.REPORT_TRANSACTIONS REORGANIZE
ALTER INDEX IX_TRAN_CREATED_COD_SIT ON dbo.[TRANSACTION] REORGANIZE
ALTER INDEX PK__SPLIT_PE__338DFC40958CAB62 ON dbo.SPLIT_PENDING REORGANIZE
ALTER INDEX PK_ASS_TAX_DEPART ON dbo.ASS_TAX_DEPART REORGANIZE
ALTER INDEX PK__ASS_TRAN__AC3553138B8E1164 ON dbo.ASS_TRANSACTION_LINK REORGANIZE
ALTER INDEX PK_USERS_LOG ON dbo.USERS_LOG REORGANIZE
ALTER INDEX PK_RESEARCH_RISK_RESPONSE ON dbo.RESEARCH_RISK_RESPONSE REORGANIZE
ALTER INDEX IX_REPORT_CONS_TRAN_CODE_COMP_SITUATION ON dbo.REPORT_CONSOLIDATED_TRANS_SUB REORGANIZE
ALTER INDEX PK_DEPARTMENTS_BRANCH ON dbo.DEPARTMENTS_BRANCH REORGANIZE
ALTER INDEX PK_POSWEB_DATA_TRANSACTION ON dbo.POSWEB_DATA_TRANSACTION REORGANIZE
ALTER INDEX IX_PROTOCOLS_CREATED_IC_PROTOCOL ON dbo.PROTOCOLS REORGANIZE
ALTER INDEX UQ_CODE_TRANSACTION ON dbo.[TRANSACTION] REORGANIZE
ALTER INDEX PK_PROCESS_BG_STATUS_ERROR ON dbo.PROCESS_BG_STATUS_ERROR REORGANIZE
ALTER INDEX PK__RISK_PER__DAA18818FA36C982 ON dbo.RISK_PERSON REORGANIZE
ALTER INDEX IX_REPORT_TRAN_COD_TRAN ON dbo.REPORT_TRANSACTIONS REORGANIZE
ALTER INDEX PK_FINANCIAL_BILLET ON dbo.FINANCIAL_BILLET REORGANIZE
ALTER INDEX PK_HIST_SIT_DOCS_BRANCH ON dbo.HIST_SIT_DOCS_BRANCH REORGANIZE
ALTER INDEX UK_TRAN_BILLET_CODE ON dbo.BILLET_TRANSACTION REORGANIZE
ALTER INDEX PK__DETAIL_R__7252D5EE11EED00C ON dbo.DETAIL_RISK REORGANIZE
ALTER INDEX IX_REPORT_CONS_TRAN_DATE_ON_CONSOLIDADED ON dbo.REPORT_CONSOLIDATED_TRANS_SUB REORGANIZE
ALTER INDEX IX_SERVICES_USING_TRAN ON dbo.TRANSACTION_SERVICES REORGANIZE
ALTER INDEX PK_BILLET_TRANSACTION ON dbo.BILLET_TRANSACTION REORGANIZE
ALTER INDEX IX_BRANCH_DEPART_COD_BRANCH ON dbo.DEPARTMENTS_BRANCH REORGANIZE
ALTER INDEX IX_REPORT_TRANS_DATA_COMP_EC ON dbo.REPORT_TRANSACTIONS_EXP REORGANIZE
ALTER INDEX IX_TRAN_SERIVCES_CODTRAN ON dbo.TRANSACTION_SERVICES REORGANIZE
ALTER INDEX PK_TRANSACTION_SERVICES ON dbo.TRANSACTION_SERVICES REORGANIZE
ALTER INDEX PK_NEIGHBORDHOOD ON dbo.NEIGHBORHOOD REORGANIZE
ALTER INDEX PK_COD_EQUIP_MIGRATE ON dbo.EQUIPMENTS_TOMIGRATE REORGANIZE
ALTER INDEX PK_COD_FIN_SCH_HISTORY ON dbo.FINANCE_SCHEDULE_HISTORY REORGANIZE

UPDATE STATISTICS ROUTE_ACQUIRER
UPDATE STATISTICS TEMP_TOKEN
UPDATE STATISTICS DOCS_BRANCH
UPDATE STATISTICS MESSAGING
UPDATE STATISTICS PROTOCOLS
UPDATE STATISTICS ROUTE_ACQUIRER_HIST
UPDATE STATISTICS DATA_EQUIPMENT_AC
UPDATE STATISTICS EQUIPMENT
UPDATE STATISTICS DENIED_ACCESS_USER
UPDATE STATISTICS ASS_DEPTO_EQUIP
UPDATE STATISTICS "STATE"
UPDATE STATISTICS DATA_TID_AVAILABLE_EC
UPDATE STATISTICS SERVICES_AVAILABLE
UPDATE STATISTICS REQ_LANGUAGE_COMERCIAL
UPDATE STATISTICS RESEARCH_RISK
UPDATE STATISTICS ASS_CERC_EC
UPDATE STATISTICS "Job"
UPDATE STATISTICS "PLAN"
UPDATE STATISTICS "Set"
UPDATE STATISTICS JobParameter
UPDATE STATISTICS ADITIONAL_DATA_TYPE_EC
UPDATE STATISTICS DEPARTMENTS_BRANCH
UPDATE STATISTICS BANK_DETAILS_CERC_INFO
UPDATE STATISTICS USERS
UPDATE STATISTICS "Hash"
UPDATE STATISTICS PAYMENT_LINK
UPDATE STATISTICS THEMES
UPDATE STATISTICS ESTABLISHMENT_CONDITIONS_HIST
UPDATE STATISTICS CERC_FILE
UPDATE STATISTICS BILLET_TRANSACTION
UPDATE STATISTICS ASS_EC_EXTERNAL_API
UPDATE STATISTICS ADDRESS_AFFILIATOR
UPDATE STATISTICS RISK_PERSON
UPDATE STATISTICS AFFILIATOR_CONTACT
UPDATE STATISTICS ADDRESS_SALES_REP
UPDATE STATISTICS CONTACT_SALES_REP
UPDATE STATISTICS ITENS_PROG_COST_AFF
UPDATE STATISTICS AFFILIATOR
UPDATE STATISTICS ACCESS_APPAPI
UPDATE STATISTICS SALES_REPRESENTATIVE
UPDATE STATISTICS PRODUCTS_ACQUIRER
UPDATE STATISTICS ASS_TR_TYPE_COMP
UPDATE STATISTICS TMP_PROMOCODE
UPDATE STATISTICS FINANCE_FILE_DISSOCIATED
UPDATE STATISTICS CUSTOMER_LINK
UPDATE STATISTICS CELER_PAY_REQUEST_HISTORY
UPDATE STATISTICS DOCS_AFFILIATOR
UPDATE STATISTICS TYPE_TARIFF
UPDATE STATISTICS TRANSACTION_TITLES_DUPLICATED
UPDATE STATISTICS MERCHANTS_INTEGRATION
UPDATE STATISTICS PROGRESSIVE_COST_AFFILIATOR
UPDATE STATISTICS ASS_PLAN_TYPE_ESTAB
UPDATE STATISTICS ASS_EC_TRAN_PRODUCT
UPDATE STATISTICS BANKS
UPDATE STATISTICS SPLIT_PRODUCTS
UPDATE STATISTICS AggregatedCounter
UPDATE STATISTICS ASS_PARAMS_PRODUCTS
UPDATE STATISTICS NOTIFICATION_MESSAGES
UPDATE STATISTICS REGISTER_ARCHIVE_EC_ELO
UPDATE STATISTICS Server
UPDATE STATISTICS ADDRESS_ADT_EC
UPDATE STATISTICS CONTRACTS_AFFILIATOR
UPDATE STATISTICS BRANCH_BUSINESS